### ISSUE TITLE
[BUG] Add-PnPContentTypesFromContentTypeHub - Not syncing to the current site

### ISSUE THREAD

**Issue by chaitanya-SharePoint** [pnp/powershell#1015]
### 
Add-PnPContentTypesFromContentTypeHub - Not syncing to current site

### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
To sync the published content types in to the current site

### Actual behavior 
Command runs without any error, but no Content Types are synced in to the current site

### Steps to reproduce behavior

`  Connect-PnPOnline -Url $siteUrl -UseWebLogin`
   ` $ctHubUrl = Get-PnPContentTypePublishingHubUrl`
    `Connect-PnPOnline -Url $ctHubUrl -UseWebLogin`
    `$CTIds = Get-PnPContentType`
    `$list = New-Object Collections.Generic.List[string]`
    `foreach($id in $CTIds){`
    `    $list.Add($id.Id.StringValue)`
    `}`
    `Connect-PnPOnline -Url $siteUrl -UseWebLogin`
    `Add-PnPContentTypesFromContentTypeHub -ContentTypes $list`

### What is the version of the Cmdlet module you are running?
 1.7.0 

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by robertcaretta** [comment]
@kilasuit - We are running into the same issues reported here, and also on [this ticket](https://github.com/pnp/powershell/issues/1080).  I have some questions about your "do until" example.  

- Have you gotten past the position 248 error? If so, what was the solution?
- What are you targeting with $ContentTypesMatchString?  Are you just check for specific named content types from the list of IDs?

**Comment by kilasuit** [comment]
@robertcaretta  
> - Have you gotten past the position 248 error? If so, what was the solution?

The above code sample doesn't care if it errors or not with `-ErrorAction SilentlyContinue` and as I am looping and retrying until I know it's worked, I chose not to care about it erroring
> - What are you targeting with $ContentTypesMatchString? Are you just checking for specific named content types from the list of IDs?

I have a prebuilt string that contains the names of all of the content types I want pulled into the site like so `"DocOwner|DocAuthoringTeam"`

**Comment by robertcaretta** [comment]
@kilasuit - Thank you for the quick response! We updated the SPO and PnP modules to the latest versions.  We tried the "do until" approach and unfortunately it just ran without success. So we terminated the command. 

Here is the change Microsoft made recently regarding the content type publishing.
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=70795

It appears we may be in a catch-22 scenario where we can't add the content type, and until we add it the new sync process will not start.

**Comment by dreamweaver9962** [comment]
Hi All,

I have been struggling with this issue for long time. Considering that the content type auto sync mechanism will be end by mid of feb I need to find a solution by that time. Not getting enough support from Microsoft regarding this issue. My code is as below

$ctHubUrl = Get-PnPContentTypePublishingHubUrl 
Connect-PnPOnline -Url $ctHubUrl 
$CTIds = Get-PnPContentType 
Write-Output 'Count:' $CTIds.Count
$list = New-Object Collections.Generic.List[string]
     foreach($id in $CTIds)
     { 
         $list.Add($id.Id.StringValue) 
     }
Add-PnPContentTypesFromContentTypeHub -ContentTypes $list -Connection $site
Start-Sleep -s 60
$SiteContnetTypes= Get-PnPContentType -InSiteHierarchy -Connection $site
Write-Output 'Count:' $CTIds.Count

After running this code I got the error  'The type of data at position 280 is different than the one expected.' But I confirmed that the count of content types in the hub and new site are the same using above code.

To verify the same using the UI I checked the Content type gallery (/_layouts/15/SiteAdmin.aspx#/contentTypes) of the new site, I can see that all content types are added but if check the classic UI (/_layouts/15/mngctype.aspx) custom content types are not appearing there.

Is this an expected behavior?

What I want to do is, I want to add a content type to the list using site design script. Previously we were relaying on 1 hour delay to sync the content types to the new site. Now we removed it and tried the above code, but the problem is site design is not adding the content type to the list. I also tried the command Add-PnPContentTypeToList, which is also not working.

This will work if we wait for 1 hour and  classic UI is populated with all the content types. Any idea on this issue?

**Comment by dreamweaver9962** [comment]
I also noticed that even if we don't run the above code, immediately after creating the site  Content type gallery (/_layouts/15/SiteAdmin.aspx#/contentTypes) will have all the custom content types populated by default. Not sure if this be the case once MS turn off content type sync in feb.

**Comment by robertcaretta** [comment]
Side note, has anyone looked into these SPO content type replication cmdlets? There is a Get and a Set.  
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/?view=sharepoint-ps

When I run the get cmdlet "Get-SPOTenantContentTypeReplicationParameters" I receive an error that "specified method is not supported".   I am using the latest version of the module too.

![2021-12-21_16-18-15](https://user-images.githubusercontent.com/1613085/147110508-1b1364c9-1b86-48c6-926b-3a34bb32e5f3.png)

**Comment by kilasuit** [comment]
@robertcaretta / @dreamweaver9962 - The reason why I chose a `do until` loopin my sample above was that I had varience in time for it to be successful and this was the simplest way to code defensively around waiting for it with a guessed delay for it to be as I expected it to be. 

@dreamweaver9962 - I'd be tempted to suggest doing this for only a few content types at a time instead of all of them as there are many that you'll have in the Content Type hub that are default anyway and do not need to be force replicated to new site collections

**Comment by dreamweaver9962** [comment]
@kilasuit I tried with three content types, still no luck. Could you please check /_layouts/15/mngctype.aspx this link after running your code, just to confirm that the newly added content types are appearing here as well.

**Comment by kilasuit** [comment]
@dreamweaver9962 - this is running on a client's tenant where I tested this extensively before they signed off that it does work as intended and were further added to any libraries that used them.

As the older content type page `/_layouts/15/mngctype.aspx` are being replaced for the newer one, I can't say I ever checked that as I was more caring about my site creation code doing what I wanted it to do for this particular client.

**Comment by dreamweaver9962** [comment]
@kilasuit As I mentioned earlier the new Content-type gallery will have all the content types even without running the code,it might be because auto-sync is still working. After adding the content types to the site are you adding the content type to the list? I'm facing the issue in that step I tried using PNP (Add-PnPContentTypeToList), Flow, and site script. All were failing because the content types are not available on the site. I think it's basically checking this path /_layouts/15/mngctype.aspx rather than the modern content type hub.

**Comment by kilasuit** [comment]
@dreamweaver9962 - like I mentioned earlier on I am doing [this](https://github.com/pnp/powershell/issues/1015#issuecomment-952730329) in a `do until` loop and only  once that until statement is true will my script then move on and add the ContentTypes to the Libraries as needed, all in a PowerShell script using 1.8.0 of the PnP.PowerShell module. 

The process I have is clear in code but to break it down

- I attempt to add the content types to the site using Add-PnPContentTypesFromContentTypeHub choosing to sliently continue on any warnings or errors 
  - I sleep for 30 seconds
  - I check if the content types are available using Get-PnPContentType as the above task withing Add-PnPContentTypesFromContentTypeHub isn't synchronous but actually asynchronous which really goes against typical PowerShell scripting expectations and can take any length of minutes to complete (hence a do until loop and not a static single sleep length)
    - If not I loop back through the above and continually retry to add them until my check confirms that they are available due to the asynchronous nature of Add-PnPContentTypesFromContentTypeHub
-Once they are I then create the required lists & libraries
  - I then add the contentTypes to the correct libraries using Add-PnPContentTypeToList cmdlet 

>I think it's basically checking this path /_layouts/15/mngctype.aspx rather than the modern content type hub.

Sorry that's not what I have seen to be the case as this has been working on a clients prod tenant, thier test tenant and multiple other test tenants (which I no longer have access to) using code to check as detailed above and then add to lists/libraries when available.

**Comment by gautamdsheth** [comment]
@chaitanya-SharePoint / @robertcaretta /  @kilasuit  / @dreamweaver9962  - is this still happening in your tenants ? Maybe you can try with the latest 1.9.0 or nightly build and let us know ? Microsoft did add some methods to publish/unpublish as well as get the status of the content type. Maybe that can help you out ? 

https://pnp.github.io/powershell/cmdlets/Get-PnPContentTypePublishingStatus.html

https://pnp.github.io/powershell/cmdlets/Unpublish-PnPContentType.html

https://pnp.github.io/powershell/cmdlets/Publish-PnPContentType.html

**Comment by veronicageek** [comment]
Closing as no response.
