### ISSUE TITLE
[FEATURE] New-PnPSite Owner and Owners Object Check

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1083]
**Is your feature request related to a problem? Please describe.**
In ```PnP.PowerShell 1.7.44``` it's possible to provide a group in ```Owner``` or ```Owners``` parameters (depending on the chosen site type). However, if a group is specified, ```New-PnPSite``` would silently ignore ```Owner``` and make a user running ```New-PnPSite``` the owner as if the ```Owner``` parameter would not be specified at all.

**Describe the solution you'd like**
It would be handful if ```New-PnPSite``` would check an object within ```Owner``` and ```Owners``` parameter and if it is not of a user type, throw an error.

**Describe alternatives you've considered**
Is there currently a way of solving your problem with existing cmdlets? Optionally through the use of other PowerShell Modules (for instance by using the Microsoft Graph cmdlets or the Microsoft SPO Management Shell)

**Comment by gautamdsheth** [comment]
Thanks for this feature request.
We wont be doing this because of performance considerations.

The Owners parameter for Team sites itself allows upto 20 users. 
If we add a check for this, then it will take time for to process each of them each.
Besides that, this is something the person executing the cmd should keep in mind before.  
We have already documented this in our docs as well about that it requires as user object.
