### ISSUE TITLE
[BUG] Add-PnPPage throwing Requested value StandardUS was not found.

### ISSUE THREAD

**Issue by HeatherWaterman** [pnp/powershell#1154]
I am troubleshooting an issue on my site and this is one of the commands I need to run.

**Running stable build 1.5.0**
Command  Add-PnPPage -Name "NewPage"

**Error I am receiving is:**

[Exception.txt](https://github.com/pnp/powershell/files/7214063/Exception.txt)
![Screenshot 2021-09-22 175735](https://user-images.githubusercontent.com/29203625/134427636-fecec2c1-6d14-499d-a787-4e7f86cb3c6b.png)

I have attached the get exception for the error.

**Comment by veronicageek** [comment]
@HeatherWaterman - Please DO NOT delete the template when creating an issue. It's there to be filled. 
Also, the latest major version is `1.7.0` or you've got nightly releases as well. **Meanwhile, please fill the below:**


### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by HeatherWaterman** [comment]
**Reporting Issue**
Unable to create a page using Add-PnPPage
**Expected Behavior**
I would expect an output showing that a page has been created with the name I provided
**Actual Behavior**

![Screenshot 2021-09-23 094959](https://user-images.githubusercontent.com/29203625/134519663-40f30959-1e58-450f-94ae-16ed4d544e27.png)
**Steps to reproduce**
![Screenshot 2021-09-23 082234](https://user-images.githubusercontent.com/29203625/134505953-b51d4cd8-67e0-4a87-acdc-f3699fde76ae.png)
**What is the version of the Cmdlet module you are running**
Updated to PS 7.14 and PNPPS 1.7
**OS Evironment**
Windows 10

**Comment by veronicageek** [comment]
@HeatherWaterman - Is your goal to create a new page and then change the name?

**Comment by HeatherWaterman** [comment]
@veronicageek  The problem is with Add Page - I can't get past that without getting the StandardUS error.

**Comment by veronicageek** [comment]
Can you try the following:

```powershell
$newPage = 'myPageName'
Add-PnPPage -Name $newPage -LayoutType Article | Set-PnPPage -Name $newPage -Title 'My Test Page' -CommentsEnabled:$false
```

Can you also test your script & the script above on another site?

**Comment by HeatherWaterman** [comment]
@veronicageek  yes I will try that. MSFT support is having me run some scripts as we can't create a new page on our root site for some reason.

**Comment by HeatherWaterman** [comment]
@veronicageek  it did not work on my site but it worked on the other site. Thanks! I will report back to MSFT support.
