### ISSUE TITLE
[BUG] - Get-PnPTenantSite - Always returns 0's (zeros) for WebsCount

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#1205]
### Reporting an Issue or Missing Feature
WebsCount column reports nothing but 0's (zeros).

### Expected behavior 
Subsite (Web) count should be reflected in the WebsCount column.

### Actual behavior 
I see nothing but 0's (zeros) in the WebsCount column. I tested this by creating a sub-site on a private channel site, then re-ran the script, and expoorted to a CSV file. Still reports zero.  I reviewed the data in the PS Object prior to exporting as well. Same values of 0.

### Steps to reproduce behavior
$allSites = Get-PnPTenantSite -Detailed
$allSites | Export-CSV -Path "$dir\csv\AllSites.csv" -NoTypeInformation -Force

### What is the version of the Cmdlet module you are running?
1.7.68

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment]
Looked into this. Unfortunately this is due to a server side issue over which we have no control. One way to work around this would be to execute your query like this:

```powershell
Get-PnPTenantSite | % { Get-PnPTenantSite -Identity $_.Url } | Select Url, WebsCount | fl
```

This will return each of your site collections with the WebsCount provided:

![image](https://user-images.githubusercontent.com/5940670/135926344-b42842de-75b7-4b9e-8ccd-bd9d084e1ee0.png)

It will make one extra API call per site collection though, so it will be slower and may run into throttling. Only other way would be to file a support case with Microsoft, but in all honesty I see little chance of them going to fix this.

Let us know if any other guidance from our side is needed.

**Comment by robertcaretta** [comment]
Thank you for that explanation and example. That helps. I'm not going to
bother opening a ticket with Microsoft.  I see I can use the Get-PnPSubWeb
-Recurse option too. That seems to provide a bit more flexibility if I want
to just get the root count, or all the children.

Go ahead and close this. :)
