### ISSUE TITLE
[BUG] Cmdlets occassionally erroring

### ISSUE THREAD

**Issue by kilasuit** [pnp/powershell#1306]
### Reporting an Issue or Missing Feature
Some cmdlets in a script can occasionally error with `The object id "site:<GUID>:web:<GUID>" is invalid.`

This seems to me to point to there being some cache of the site/web in the execution of some cmdlets, noticably with the `PnPContentTypesFromContentTypeHub` & `Get-PnpContentType` & `Set-PnPWebPermission`

### Expected behavior 
No Error to occur.

### Actual behavior 
This error occurs.

### Steps to reproduce behavior

1. Build a list of new sites to create (10+)
2. Loop through List creating new sites 
3. Connect to new site
4. Get Web Object in `$web` var
5. Enable Pubishing Feature
6. Add Permissions using `Set-PnPWebPermission` `//errors` 
6. Pull content types from CTHub with this [code](https://github.com/pnp/powershell/issues/1015#issuecomment-952730329) `//errors` 
7. Add additional lists
8. Attempt to add CT's from CTHub to lists using similar [code](https://github.com/pnp/powershell/issues/1015#issuecomment-952730329) to this `//errors` 
9. Ensure to disconnect-pnponline
10. ensure to null out `$web`
11. Loop onto next site

Occasionally get stuck with this error loop within any of those 10 sites to create

(I can't share the exact code but can if needs try and provide a sanitised version)

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [ x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Can you please try with the latest 1.10 or maybe the nightly builds if possible ? 

At time of this issue, I guess the content type methods were quite new and maybe not propagated correctly to all tenants, but should be fixed by now.

About this error `The object id "site:<GUID>:web:<GUID>" is invalid.` , it usually occurs when you are using a site collection  which was deleted and recreated again. 

There is no caching going for any of the cmdlets , the error that you mentioned comes from CSOM SDK directly.  It is a server side issue.
If you would try that on a fresh, new site collection, this error doesn't occur.

**Comment by kilasuit** [comment]
Hi @gautamdsheth that all makes sense as this was on site collections that where being deleted and recreated again & like you said the content type methods weren't fully propagated which may have also impacted this too.

I currently don't have the time to check it or the similar infrastructure to do so but I am happy to take your word about this being the root cause of this issue.

**Comment by gautamdsheth** [comment]
Thanks for getting back !
Will close this issue , please create a new one if something like this happens.
