### ISSUE TITLE
[BUG] New-PnPSite for Team Sites and w/App-Only Auth (still) ignoring Lcid-parameter

### ISSUE THREAD

**Issue by balle3201** [pnp/powershell#1392]
### Reporting an Issue or Missing Feature
Creating new Team Sites by using New-PnPSite (-Type TeamSite) w/App Only Auth while specifying Lcid always resulting in tenant's default-language Team Sites. Example: New-PnPSite -Type TeamSite -Lcid 1044 => English Site (1033)

### Expected behavior 
The expected behaviour would be that the resulting Team Site gets created with the correct default language, as specified by the Lcid-parameter

### Actual behavior 
Team Sites created with App-Only Auth and Lcid-parameter gets created with the tenant's default language (in our case, English 1033)

### Steps to reproduce behavior
Create a new Team Site (w/App-Only Auth) with Lcid (other than tenant's default language). The resulting Team Site is created with incorrect language.

NB! Running the exact same command while using standard/normal auth (i.e. Interactive) works as intended. It seems to be only affected while using App-Only Auth.

### What is the version of the Cmdlet module you are running?
PnP PowerShell 1.7.0 & 1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi this is unfortunately not possible due API limitations.

For app-only, we use Microsoft Graph API to create the modern team site with M365 Group.
For user interactive , we use standard SharePoint API to create the site because App-only is not supported for SharePoint APIs.

The issue with Graph API is that it doesn't expose LCID property , so it will always pick the default tenant language.

We can't do anything from the PnP side , so would suggest that you create a feature request for the Microsoft Graph product team.
Closing this issue now.
