### ISSUE TITLE
Get-PnPTeamsTab : Invalid filter clause

### ISSUE THREAD

**Issue by ITAndy23** [pnp/powershell#1416]
Using PowerShell v5.x

Getting error:
  Get-PnPTeamsTab : Invalid filter clause
  At line:11 char:20
  $allTabs = Get-PnPTeamsTab -Team $team.DisplayName -Channel $channel ...
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CategoryInfo          : InvalidOperation: (:) [Get-PnPTeamsTab], PSInvalidOperationException
  FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Graph.GetTeamsTab

This is line 11:
`$allTabs = Get-PnPTeamsTab -Team $team.DisplayName -Channel $channel`

**Comment by LeonArmston** [comment]
Can you say what values $team.DisplayName and $channel are returning? We will need more details to troubleshoot?

Is it failing on all team display names? As I'm wondering if it may be due to special characters or something....

Is $channel a channel ID or display name or even a channel object retrieved using Get-PnPTeamsChannel

It would help us if you could fill in the details below:

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@LeonArmston - Thanks for your input.

@ITAndy23 - Tried with `1.8.0` and PowerShell `5.1` but no issue with the command itself. Please reopen the issue with the template filled out and more details so we can try to help you if the problem persists.

![image](https://user-images.githubusercontent.com/25181757/145011031-5609b2fe-5917-4988-85c9-9e80689da3ab.png)
