### ISSUE TITLE
(Get-PnPTenantSite).IsHubSite always returns False

### ISSUE THREAD

**Issue by Ambergahill** [pnp/powershell#1439]
This is the same issue as https://github.com/pnp/powershell/issues/151, but it looks like the bug was reintroduced. I am using version 1.7.0

**Comment by veronicageek** [comment]
@Ambergahill - I have no issue with `1.8.66` (latest nightly release). so please update your module to at least the major `1.8.0`.

When opening an issue, please DO NOT DELETE the template. If your issue is similar to another one, then just reopen the other issue so we can look at the thread all in one place. Thanks.

![image](https://user-images.githubusercontent.com/25181757/145875372-c2136db6-c381-44da-9fd2-2e0d52e572ba.png)

**Comment by Ambergahill** [comment]
I don't know what you mean by do not delete template. I just clicked on New issue. i will test with 1.8.0 and reopen #151 if needed. Thanks

**Comment by Ambergahill** [comment]
The problem is when you get your sites via something like $allSites = Get-PnPTenantSite -Detailed ....then get the isHubSite property on the results returned, it doesn't work

**Comment by Ambergahill** [comment]
I opened up https://github.com/pnp/powershell/issues/1449 since it is technically a different issue than #151
