### ISSUE TITLE
[BUG] Copy-PnPFile does not work between GEO sites

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#1446]
### Reporting an Issue or Missing Feature
Bug

### Expected behavior 
Successful copy file

### Actual behavior 
![image](https://user-images.githubusercontent.com/12259728/146091667-0e76e125-e61d-4613-82e1-b1e23ddc4a3b.png)

### Steps to reproduce behavior
Copy-PnPFile -SourceUrl "https://xyznam.sharepoint.com/sites/sitea/Shared Documents/file.xlsx" -TargetUrl "https://xyzaus.sharepoint.com/sites/siteb/Shared Documents" -Force

### What is the version of the Cmdlet module you are running?
1.8

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @svermaak , we have improved the cmdlet and have potentially fixed this issue with the latest nightly builds.

You will need to provide a full destination URL for this to work.
i.e , the  -TargetUrl parameter value needs to be something like `https://xyzaus.sharepoint.com/sites/siteb/Shared DOcuments/test.docx`

The source URL value should be a server relative URL like `/sites/test/Shared Documents/test.docx`.

Please let us know if it works at your end. We can't say for sure because we dont have access to multi-geo envs.
