### ISSUE TITLE
[BUG] Content Types returned from Get-PnPContentType have undefined parent values

### ISSUE THREAD

**Issue by MDGH2021** [pnp/powershell#1457]
### Reporting an Issue or Missing Feature
The objects returned from Get-PnPContentType do not have parent content type information. The .parent method on the objects is always empty despite always being defined in the content type, regardless if it is custom or Document/Item. 

### Expected behavior 
Should contain name of parent content type. 

### Actual behavior 
Is always empty. 

### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/96268532/146461432-9c44aace-368b-43fb-90c1-691ef6893bde.png)

### What is the version of the Cmdlet module you are running?
PnP.Powershell 1.8

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by LeonArmston** [comment]
The content type property value is not returned by default due to the nature of CSOM only retrieving a small number of necessary properties. The is to save internet bandwidth & backend resource bandwidth.

You can use [**Get-PnPProperty**](https://github.com/pnp/powershell/blob/dev/documentation/Get-PnPProperty.md) to retrieve the Content Type parent property like the below

```powershell
$contentType = Get-PnPContentType -Identity "Report"

Get-PnPProperty -ClientObject $contentType -Property Parent

$contentType.parent
```
![image](https://user-images.githubusercontent.com/12968962/146607645-de82caa6-4cad-4632-9b10-f9a80c62a3ee.png)

Some PnP SharePoint Get commands i.e. Get-PnPList have a -Includes parameter for requesting additional properties but Get-PnPContentType does not have this at the moment.

**Comment by MDGH2021** [comment]
Thank you Leon this is perfect.
