### ISSUE TITLE
[FEATURE] - Get-PnPTenantSite - Created Date

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#1541]
**Is your feature request related to a problem? Please describe.**
The problem with this command is it does not return the created date of each site.

**Describe the solution you'd like**
Ideally the results return the created date. Then I can filter down to specific template IDs and created date for daily processing.

**Describe alternatives you've considered**
Potentially pulling data from the hidden "DO_NOT_DELETE_SPLIST_TENANTADMIN_AGGREGATED_SITECOLLECTIONS"

**Additional context**
N/A

**Comment by gautamdsheth** [comment]
Hi @robertcaretta , the issue here is that we are not getting this value from SharePoint services.
We use the underlying CSOM SDK which retrieves a lot of the properties but unfortunately created date is not one of them. 
So, we wont be able to extend it to fetch it using the `Get-PnPTenantSite` cmdlet.
Will be closing the feature request due to this limitation.
