### ISSUE TITLE
[BUG] Cannot use Get-PnPListItem with Query on list with most than 5000 items

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#1550]
### Reporting an Issue or Missing Feature
Cannot use Get-PnPListItem with Query on list with most than 5000 items

### Expected behavior 
The same results as Get-PnPListItem with PageSize but limited to the query

### Actual behavior 
Get-PnPListItem: The attempted operation is prohibited because it exceeds the list view threshold.
![image](https://user-images.githubusercontent.com/12259728/150699246-1f14f2a4-d666-46d0-9e61-80a1351462d6.png)

### Steps to reproduce behavior
Get-PnPListItem -PageSize 5000 -List "Shared Documents" -Query "<View Scope=""RecursiveAll""><Query><Where><Contains><FieldRef Name='FileLeafRef'/><Value Type='Note'>.msg</Value></Contains></Where></Query></View>"

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by svermaak** [comment]
Any ideas?

**Comment by svermaak** [comment]
Any ideas?

**Comment by JazBInKC** [comment]
I believe -Query and -PageSize coding (GetListItem.cs) are such that the built -Query overrides the "query" otherwise created when NOT using -Query.  I think the solution is to include the <Row> (<Rows>?) parameter in you query to limit pages to 5000 or less.

**Comment by gautamdsheth** [comment]
You need to ensure that the column that you use in the CAML query is an indexed column. 
If that column is not indexed, then you will have threshold issues.

For example, ID column is indexed , so if you create a query using that column, like ID > 1 and ID < 4000, it will work with pagesize and then you can iterate and increase the ID values. 
Ofcourse, you need to mark a column as indexed column before the list hits the 5000 limit. 

Am moving this to a discussion because its a question and not a PnP PowerShell issue.
