### ISSUE TITLE
[BUG] - PnP login seems to rely on basic authentication

### ISSUE THREAD

**Issue by tomko80** [pnp/powershell#1558]
### Reporting an Issue or Missing Feature
The PnP login seems to rely on basic authentication (missing feature). Microsoft has announced in 2021 that use of basic authentication is currently being depreciated: https://docs.microsoft.com/en-us/lifecycle/announcements/exchange-online-basic-auth-deprecated

### Expected behavior 
Successfully sign in using user credentials (limited delegated access) when basic authentication has been disabled.

### Actual behavior 
Error:
```
Connect-PnPOnline: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '000000000...'.
Trace ID: 34a659a7-3df2-46f7-843a-8db05f2a0e12
Correlation ID: c1c85c96-3012-42b1-8e33-e954336236f9
Timestamp: 2022-01-26 10:06:29Z
```
Allowing the basic authentication for the account using policy results in the expected behavior.

### Steps to reproduce behavior

1. Disable basic authentication for all users of tenant.
2. Run:

```
save-module -name PnP.PowerShell -path c:\temp\test\lib
import-module "C:\temp\test\lib\PnP.PowerShell\1.9.0\PnP.PowerShell.psd1"
$siteUrl = "https://xyz.sharepoint.com/sites/123/"
Connect-PnPOnline -Url $siteUrl -Credentials (Get-Credential)
```

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
You can use the interactive parameter  I guess instead of this

`Connect-PnPOnline -Url $siteUrl -Interactive`

**Comment by tomko80** [comment]
> You can use the interactive parameter I guess instead of this
> 
> `Connect-PnPOnline -Url $siteUrl -Interactive`

Not an option for me as I need headless login (the script runs as a job).

I found that the graph permission Sites.Selected can now be used to limit the access using client id and secret as the credentials. (had to use a account before to restrict the access scope) BUT

When I run:
`Connect-PnPOnline -Url "https://andritz.sharepoint.com/sites/10482/" -ClientId "xyz" -ClientSecret "xyz"
`
I get the message
```
WARNING:
 Connecting with Client Secret **uses legacy authentication** and provides limited functionality. We can for instance
 not execute requests towards the Microsoft Graph, which limits cmdlets related to Microsoft Teams, Microsoft
 Planner, Microsoft Flow and Microsoft 365 Groups. You can hide this warning by using Connect-PnPOnline [your
 parameters] -WarningAction Ignore
```

So dead end?

**Comment by gautamdsheth** [comment]
This is by design, we use MSAL.NET behind the scenes. In case of Conditional Access, it will not work - 

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#usernamepassword

For headless scenario, would recommend use of ClientId and Certificate like:

https://pnp.github.io/powershell/articles/connecting.html#connect-using-a-clientid-and-pfx-certificate-stored-on-your-local-machine

or

https://pnp.github.io/powershell/articles/connecting.html#connect-using-a-clientid-and-pfx-certificate-stored-in-the-windows-certificate-management-store

As to the error that you described, Graph Sites.Selected is used for Graph API calls whereas Get-PnPSite relies on SharePoint CSOM , so it will not work. You will need to use SharePoint Sites.Selected permissions for this.

https://www.leonarmston.com/2022/01/pnp-powershell-csom-now-works-with-sharepoint-sites-selected-permission-using-azure-ad-app/

**Comment by gautamdsheth** [comment]
Hi @tomko80 , any luck with these approaches that I mentioned ?

**Comment by gautamdsheth** [comment]
Closing it as no response.
