### ISSUE TITLE
[BUG] Get-PnPTenantSite not getting SensitivityLabel property when getting all sites

### ISSUE THREAD

**Issue by christouuu** [pnp/powershell#1623]
### Reporting an Issue or Missing Feature
Issue in the get all sites mode of Get-PnPTenantSite

### Expected behavior 
Only when getting all sites : expect to see the SensitivityLabel of each site filled with a GUID of a label, when there is one set on the site

### Actual behavior 
When getting all sites, the SensitivityLabel property of every site is empty 
When getting one specific site using the -Identity argument, the SensitivityLabel is well set 

### Steps to reproduce behavior
$allSites = Get-PnPTenantSite; # all sites have SensitivityLabel property empty ie : $allSites[0].SensitivityLabel
$oneSite = Get-PnPTenantSite -Identity https://mytenant.sharepoint.com/sites/mylabeledsite; # $oneSite.SensitivityLabel has a GUID

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Hi @christouuu , unfortunately this is a bug from CSOM SDK which is provided by Microsoft. We wont be able to fix it, only Microsoft can. Once they fix it, we always consume the latest CSOM version and it will be fixed here automatically. 

So, will request you to raise a ticket with Microsoft about this behavior. 
Will be closing the issue here.
