### ISSUE TITLE
Get-PnPSitePolicy returns empty on recent sites while synced Site policy is visible in UI

### ISSUE THREAD

**Issue by advdberg** [pnp/powershell#1645]
Seen in PnP PowerShell 1.7.0

On recent sites, when we execute Get-PnPSitePolicy, site policies synced from the contenttypehub are not retrieved. At the same time we do see the site policies in the SharePoint UI. Also from the UI the policy can be applied successfully.

We also see that the hidden contenttype which used to be created once the sync was done, is also not available.

We see the same behaviour on multiple tenants and it started a few weeks ago.

On older sites the policy is retrieved without any problem.

**Comment by veronicageek** [comment]
@advdberg - Please DO NOT delete the template when creating an issue. Can you please fill the following:

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Closing. Please create a new issue by filling the template if still occurs.
