### ISSUE TITLE
[BUG] -UseWebLogin needs a way to ignore existing credentials or "work/school" account you are signed into Windows

### ISSUE THREAD

**Issue by JustinGrote** [pnp/powershell#170]
Pull forward of https://github.com/pnp/PnP-PowerShell/issues/1656 which is still an issue

-ForceAuthentication or -ClearTokenCache or something like that would be ideal for the parameter name.

**Comment by jansenbe** [comment]
Doesn't -Interactive instead of -UseWebLogin work better for you?

**Comment by JustinGrote** [comment]
@jansenbe as of 1.2.0, -Interactive isn't an available switch, unless I'm missing something.

```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   1.2.0                 PnP.Powershell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPContentType…}
```

```
    Connect-PnPOnline -AADDomain <String> -ClientId <String> -ClientSecret <String> [-CreateDrive] [-DriveName <String>] [-Realm <String>] [-ReturnConnection]
    [<CommonParameters>]

    Connect-PnPOnline -AADDomain <String> [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] -ClientSecret <String> [-CreateDrive] [-DriveName
    <String>] [-Realm <String>] [-ReturnConnection] [-TenantAdminUrl <String>] [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] -ClientId <String> -ClientSecret <String> [-CreateDrive]   
    [-DriveName <String>] [-Realm <String>] [-ReturnConnection] [-TenantAdminUrl <String>] [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] -ClientId <String> [-CreateDrive] [-DriveName <String>]    
    -RedirectUri <String> [-ReturnConnection] [-TenantAdminUrl <String>] [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] [-CertificatePassword <SecureString>] [-CertificatePath   
    <String>] -ClientId <String> [-CreateDrive] [-DriveName <String>] [-ReturnConnection] -Tenant <String> [-TenantAdminUrl <String>] [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] [-CertificatePassword <SecureString>] -ClientId <String>  
    [-CreateDrive] [-DriveName <String>] [-ReturnConnection] -Tenant <String> [-TenantAdminUrl <String>] [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] -ClientId <String> [-CreateDrive] [-DriveName <String>]   
    [-ReturnConnection] -Tenant <String> [-TenantAdminUrl <String>] -Thumbprint <String> [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] -ClientId <String> [-CreateDrive] [-DriveName <String>]   
    [-ReturnConnection] -Tenant <String> [-TenantAdminUrl <String>] [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] [-LaunchBrowser] -PnPManagementShell [-ReturnConnection]  
    [<CommonParameters>]

    Connect-PnPOnline [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] [-Credentials <CredentialPipeBind>] [<CommonParameters>]

    Connect-PnPOnline [-AzureEnvironment {Production | PPE | China | Germany | USGovernment}] [-LaunchBrowser] [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-CreateDrive] [-Credentials <CredentialPipeBind>] [-DriveName <String>] [-ReturnConnection] [-TenantAdminUrl <String>]
    [-TransformationOnPrem] [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-CreateDrive] [-DriveName <String>] [-ReturnConnection] [-TenantAdminUrl <String>] -UseWebLogin [-ForceAuthentication]
    [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-CreateDrive] [-DriveName <String>] [-ReturnConnection] [-TenantAdminUrl <String>] [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-CreateDrive] [-Credentials <CredentialPipeBind>] [-DriveName <String>] [-ReturnConnection] [-TenantAdminUrl <String>]
    [<CommonParameters>]

    Connect-PnPOnline [-Url] <String> [-CreateDrive] [-DriveName <String>] [-ReturnConnection] [-TenantAdminUrl <String>] [<CommonParameters>]

    Connect-PnPOnline [[-Url] <String>] [-CreateDrive] [-DriveName <String>] [-ReturnConnection] [<CommonParameters>]
```

**Comment by jansenbe** [comment]
It's not yet in an official release but it's available in the latests nightly drops. You can use it like this:

`Connect-PnPOnline -Url https://contoso.sharepoint.com/sites/portal -Interactive`

**Comment by erwinvanhunen** [comment]
@JustinGrote  : -ForceAuthentication is actually available when using -UseWebLogin in 1.2.0. It will clear the cookies set for authentication.

**Comment by JustinGrote** [comment]
@erwinvanhunen  
![image](https://user-images.githubusercontent.com/15258962/105869299-f0448200-5fab-11eb-8ce0-d28416f8a440.png)

**Comment by erwinvanhunen** [comment]
Right. So this is puzzling. When I built the -ForceAuthentication functionality it worked normally for me. There is one difference between then and now: now I'm using a domain connected computer whereas at the time of development I was not connected to an AD. That seems to be the difference. What we do to force the authentication is that we clear the auth cookies before we show the authentication dialog. If those are present in the Windows cookie storage then you will be automatically authenticated. This behavior is different with AD joined machines it seems. Something to look into.

The null reference exception, is that because you are not specifying an URL to connect to? I'll catch that one a bit nicer in the code, but that's probably the reason you see the exception.

**Comment by erwinvanhunen** [comment]
I do second @jansenbe's remark though: consider using -Interactive when possible (it does require a Azure AD app or a consent for the PnP Management Shell multi-tenant app). The underlying authentication flow is fully supported by MS (we are using MSAL) and you will acquire a token with that can have access rights to the Graph (so for instance the Teams cmdlets, etc. etc. also work). UseWebLogin is a limited way of authentication given that it's fully cookie based and as a result we cannot access any other resources within the M365 ecosystem.

**Comment by JustinGrote** [comment]
It was -Url that was causing the null exception. Consider making it a mandatory parameter in the parameter sets that it exists if that's not a breaking change.

I grabbed the nightly and `-Interactive` behaves more like I expect MSAL-style as you say. That resolves my issue so I'll flag this as closed with the resolution "fixed in prerelease"

**Comment by JustinGrote** [comment]
@erwinvanhunen you may consider adding a -UseStart or -UseBrowser or something to use the existing browser rather than an "embedded" IE window. This is how the `Az` and `Exchange` cmdlets do it for a more consistent "feel"

**Comment by erwinvanhunen** [comment]
@JustinGrote : exactly with the weblogin method it doesn't work to launch an external browser. However, with -Interactive we do support launching an external browser, just specify `-LaunchBrowser'` Let me explain what's happening behind the scenes with weblogin:

1. We open the /_layout/settings.aspx page in the site in a popup browser. 
2. We monitor the navigation events and the moment we have a known set of cookies present we take those cookies out of the browser and store them in a new cookiecontainer
3. We close the popup browser
4. We create a new clientcontext behind the scenes and override the webexecute request and inject the cookies in every request we make, thus authenticating the request.

For that we need full control over the brower in order to 'catch' the cookies. If we would launch a browser separately we cannot hook into that browser to retrieve the cookies. 

This is exactly one of the reasons we don't necessarily like the UseWebLogin method. It's too error-prone.

However, with the -Interactive login things work a bit different:

1. We launch (either a popup, or an external browser, as you can specify the -LaunchBrowser option with -Interactive) an interactive OAuth flow
2. Part of the requirement of that flow is that we specify a redirect URL. That redirect url points to localhost:[randomport]. 
3. The moment we launch the browser popup or the external one we start to listen on that random port on localhost to incoming requests
4. The moment you authenticated in the browser window Azure AD will redirect you to the localhost:[port] url, where we receive the request, extract the accesstoken from the address (it's sent to as a query parameter) and we stop listening on that port. From that moment we have a valid accesstoken that is added to the authorization header of every request we make.

This is what the Az and the Exchange cmdlets also use, as it's a supported MSAL authorization flow.

Given the fact that we get a full accesstoken to Azure resources/audiences this auth method is much more functional when compared to the much more limited cookie auth.

**Comment by JustinGrote** [comment]
@erwinvanhunen I didn't even look to see if there was a `-LaunchBrowser` parameter, oops. My bad. Glad you've put a lot of thought into it, it is much appreciated for the detailed answer!
