### ISSUE TITLE
[BUG] Unable to use application id with New-PnPTerm

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#1749]
### Reporting an Issue or Missing Feature
 Unable to use application id with New-PnPTerm

### Expected behavior 
Connect via application id with certificate and use New-PnPTerm

### Actual behavior 
New-PnPTerm: The current user has insufficient permissions to perform this operation.

### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/12259728/161885850-6f315312-4de7-49e6-8d72-9cad747dd6fa.png)

![image](https://user-images.githubusercontent.com/12259728/161885687-785b50c8-b8b7-46da-8ed7-eb3b9b32a395.png)

### What is the version of the Cmdlet module you are running?
1.10

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by milanholemans** [comment]
Hi @svermaak 

I don't think this is a PowerShell related issue, it does work for me.
In order to create terms with app only context, API permissions is strangely not enough. You have go to the classic term store manager ([https://tenant-admin.sharepoint.com/_layouts/15/TermStoreManager.aspx](https://tenant-admin.sharepoint.com/_layouts/15/TermStoreManager.aspx)) and add `app@sharepoint` as Term Store Administrator.
![image](https://user-images.githubusercontent.com/11723921/162065429-7209cea4-fbe3-45ba-a511-49e6ba53312d.png)

After this trick, you should be able to make adjustments to the term store in app only context.

**Comment by svermaak** [comment]
I will give that a go and come back

**Comment by svermaak** [comment]
@milanholemans Stellar! I really appreciate it Bud. I was skeptical but it works!
