### ISSUE TITLE
[FEATURE]Get-PnPList.MaxID

### ISSUE THREAD

**Issue by JazBInKC** [pnp/powershell#1884]
**Is your feature request related to a problem? Please describe.**
When processing large (very large) lists I'm often forced to perform Get-ListItem (repeatedly) with an increasing ID range query.   I have found no version of a (pre-) query that I can run that will give me the current highest ID value for a given List.   I can easily get the number of items in a list via `(Get-PnPList $listUrl).ItemCount`

**Describe the solution you'd like**
I'd like to make the current max ID for a list as easily accessible as the list count:

`$maxID = (Get-PnPList $listUrl).MaxID`

**Describe alternatives you've considered**
I have tried literally every query method suggested (a lot of Google time).  Most don't survive large lists, those that do return a number that never changes (11651165).  I am currently using 2 x ItemCount as my 'limit' for processing.  I don't like guessing and it makes no sense that a MaxID or NextID isn't readily available.

**Additional context**
I'm processing over 15 million files / folders daily in 2 libraries (moving a client OFF SharePoint).

**Comment by milanholemans** [comment]
Hi @JazBInKC 

As far as I know creating an extra property won't be possible. The max ID is not something we get back from the list API. In order to get the max ID, you have to create an extra query on the list items endpoint.

By using a CAML query, you are able to retrieve the item with the largest ID.
`<View Scope='RecursiveAll'><Query><OrderBy><FieldRef Name='ID' Ascending='False' /></OrderBy></Query><RowLimit>1</RowLimit></View>`
Looking at the docs, you should be able to pass a CAML query to get `Get-ListItem` cmdlet, check this [example](https://pnp.github.io/powershell/cmdlets/Get-PnPListItem.html#example-5).

So I assume when you run following command, you should be able to get the max ID.
```powershell
$items = Get-PnPListItem -List MyList -Query "<View Scope='RecursiveAll'><Query><OrderBy><FieldRef Name='ID' Ascending='False' /></OrderBy></Query><RowLimit>1</RowLimit></View>"
$maxId = $items[0].Id
```

**Comment by JazBInKC** [comment]
Appreciate the suggestion - this has been tried.  The list has over 10 million items.  Logically: correct, functionally: an eternity.   Again, surprised that there is not a single cmdlet (PnP.PowerShell or otherwise) that cannot tell one what SharePoint must know.

Thanks!

**Comment by KoenZomers** [comment]
My first thought also went to what @milanholemans recommended above. It takes an eternity in time to get a response to this query? What's an eternity in this scenario? Minutes? Would that be an issue for your scenario?

Also would question the scenario at hand a bit to be honest. If you're having lists with 12 million or more items in them, that's definitely not a good design and recommended practice, but I understand that might be besides the point since you're offboarding a customer from SharePoint. Just hoping the reason for offboarding is not due to bad architectural design and use of the product leading to dissatisfaction.

Have you tried to see if you query the SharePoint list through the [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=http) if that could help any in getting a faster response? I.e. $select=Id&$top=1? You could execute it using [Invoke-PnPGraphMethod](https://pnp.github.io/powershell/cmdlets/Invoke-PnPGraphMethod.html).

Another option could be to go with search. Assuming the list or library is getting indexed, you could theoretically construct a search query to return the item with the largest Id. Use [Submit-PnPSearchQuery](https://pnp.github.io/powershell/cmdlets/Submit-PnPSearchQuery.html) for this.

**Comment by KoenZomers** [comment]
@JazBInKC Thanks for elaborating. I'm not clear however if further help is needed from our side on this or if you have managed to find a workable situation for yourself?

**Comment by JazBInKC** [comment]
@KoenZomers - Thanks, I have a workaround.  No additional help required.
