### ISSUE TITLE
[BUG] - Authentication

### ISSUE THREAD

**Issue by paylord** [pnp/powershell#19]
### Reporting an Issue or Missing Feature
I am unable to use Connect-PnPOnline with this pre-release where I am not a global admin.

### Expected behavior 
On an environment where I am global admin:
Register-PnPManagementShellAccess (as global admin),
Connect-PnPOnline -url $url -Credentials $cred (as same global admin)
Get-PnPWeb
Shows web details as expected

This is working fine.  I also need to be able to connect in an environment where I am not a global admin.

### Actual behavior 
Get 403 error
Connect-PnPOnline : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Connect-PnPOnline -Url $url
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], WebException
    + FullyQualifiedErrorId : System.Net.WebException,PnP.PowerShell.Commands.Base.ConnectOnline

I am Site Collection Admin on the site at $url.

### Steps to reproduce behavior
On a separate environment where I am not a globlal admin but I am SP Admin:
Get global admin to run Register-PnPManagementShellAccess
Add my account as user to Enterprise App "PnP Management Shell" in Azure AD

1
Connect-PnPOnline -url $url -Credentials $cred
403 error as above

2
Register-PnPManagementShellAccess (using my account)
Connect-PnPOnline -url $url -Credentials $cred
403 error as above

3
Connect-PnPOnline -url $url
Prompts for credentials
403 error as above

4
Connect-PnPOnline -url $url -PnPManagementShell -LaunchBrowser
Browser opens, paste in code, authenticate using my creds, advised successful, close browser
No error
Get-PnPWeb
403 error as above
Get-PnPContext and Get-PnPConnection both show details including the $url above

I appreciate this may just be my lack of understanding how this is intended to work but as yet, there seems to be little documentation available.  I have just assumed that Register-PnPManagementShellAccess needed to be run by a global admin as it throws an error if run by a non global admin.

One of the reasons I am testing this early is because I need to use PnP PowerShell in an Azure function app but there is a bug in v1 functions.  How does app-only auth work?  Does it still need the Register-PnPManagementShellAccess??

### What is the version of the Cmdlet module you are running?
0.1.23

**Comment by paylord** [comment]
Just adding that -ClientId and -ClientSecret do work successfully so assume they will be fine for app-only in function app so please disregard that bit of the query above.

Thanks :)

**Comment by paylord** [comment]
Not sure if it helps but I get similar using PS7:

PS C:\Users\dapayl> Connect-PnPOnline -Url $url -Credentials $cred
PS C:\Users\dapayl> Get-PnPWeb
Get-PnPWeb: Access denied. You do not have permission to perform this action or access this resource.

In Connect-PnPOnline seems to connect OK but then the error occurs when I try to do anything.

**Comment by erwinvanhunen** [comment]
We are indeed very early in the transitioning stage to the new version of PnP PowerShell. We plan to go GA at the end of the year and until that time documentation will lack more than usual.

Register-PnPManagementShellAccess adds an entry to the Azure AD Enterprise Applications. It's a basically a registration that allows authenticated users (e.g. users able to authenticate towards the AD) to use a specified OAuth2 clientid towards SharePoint Online and the Microsoft Graph. It's very similar to creating your own clientid/secret/certificate combination and adding that to the Azure AD, with the difference that we predefined a series of permission scopes and make the clientid available as a multi-tenant application.

The cmdlet indeed needs to be executed by someone with write access to the AD, in order to successfully process that entry. It could be that the entry ended up in a 'stale' state. If you navigate to the Azure AD, go to Enterprise Applications, locate "PnP Management Shell", you can reconsent the approval from there if needed. Maybe that solves your issue?

Keep in mind, that while you can use the cmdlet to register the application, actual access to SharePoint artifacts (sites, webs, etc.) are still restricted based on the SharePoint security model.

**Comment by paylord** [comment]
@erwinvanhunen - I am working on getting a global admin to re-consent as you suggested and will let you know the result.  I have checked the Enterprise App and while it looks fine I cannot see any permissions for SharePoint:
![image](https://user-images.githubusercontent.com/8131698/98499595-b5c52600-2295-11eb-9c4b-d8b1dee22cd2.png)
Is this as expected?

My account has also been added to this Enterprise App as a User - is this actually necessary?

Also, Connect-PnPOnline using ClientID and ClientSecret is working fine.  Does this suggest that the Enterprise App is working correctly or does that connection method not actually use the app?

Sorry for so many questions!

Dave

**Comment by paylord** [comment]
Re-consent seems to have resolved the issue.  Based on this I will assume that using ClientID/ClientSecret does not actually use the Enterprise App - which makes sense as I guess it is then using its own app.

Thanks again for the great work 👍 

Dave
