### ISSUE TITLE
[BUG] Storage Limit error when Registering a site as a Hub

### ISSUE THREAD

**Issue by mhomol** [pnp/powershell#1929]
### Reporting an Issue or Missing Feature
Bug seen when performing Register-PnPHubSite

### Expected behavior 
Since the logged in user is a SharePoint Administrator, I expect this to work successfully

### Actual behavior 
I have a site in a production tenant that I created using PnP PowerShell scripts.  I am trying to register this site as a Hub site.  When I run this command in PowerShell:
`Register-PnPHubSite`
I'm getting the following error:
`This site has exceeded its maximum file storage limit. To free up space, delete files you don't need and empty the recycle bin.`
 
The site is not out of storage - I have confirmed.  Plus the action itself shouldn't even have anything to do with storage, I would think.

When I run `Get-PnPException` after getting the error, here's the full error:

```
Message          : HandleProvisioningException rethrowing: This site has exceeded its maximum file storage limit. To free up space, delete files you don't need and empty the recycle 
                   bin.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
                      at PnP.PowerShell.Commands.Admin.RegisterHubSite.ExecuteCmdlet() in c:\build\src\Commands\Admin\RegisterHubSite.cs:line 27
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 89
ScriptLineNumber : 1
```
 
Also, please NOTE that I cannot seem to register any site as a Hub in the UI of the SharePoint Admin, yet all other actions seem to work fine.  I get a pretty nondescript error, as this GIF indicates:
![Large GIF (1544x746)](https://user-images.githubusercontent.com/680566/171488088-775dd11c-d642-4eea-aee0-e50964532b36.gif)

Has anyone ever encountered anything like this?

### Steps to reproduce behavior
I cannot replicate this within other tenants and do not know how best to proceed at this point.  I would love even some advice on other things to try or check within this particular production tenant.

### What is the version of the Cmdlet module you are running?
latest

### Which operating system/environment are you running PnP PowerShell on?
- [ x] MacOS

**Comment by veronicageek** [comment]
@mhomol - The fact that this is also not possible via the UI (for this particular site) shows the cmdlet is not related. I'd suggest you open a support ticket with Microsoft directly so they can check what's happening in the backend.

**Comment by mhomol** [comment]
Is it possible that the function is giving me an incorrect error message or can I trust that this is the exact message returning from the API?

**Comment by Sketchdelite** [comment]
Hey mhomol, I'm writing because I encountered the exact same error message and managed to get to a resolution after a couple of months of talks with Microsoft Support

As you had confirmed in your case, the target site that you were trying to register as a hub site had the appropriate storage quota, or at least had a higher quota than your usage. I had checked this on my side too.

However, for my case it was not the target site that had reached it's quota limit, but the "https://tourismholdings-my.sharepoint.com" site. The personal sharepoint site for the user you happen to be logged in under.
I didn't bother asking Microsoft Support why this would be the case, but for my personal site, the quota and usage was the same (and so, maximum storage limit reached).
I bumped the quota on this site, tried registering the target site again, and it's working now! I was quite surprised.

Get-SpoSite -Identity "https://tourismholdings-my.sharepoint.com" | fl
Set-SpoSite -Identity "https://tourismholdings-my.sharepoint.com"  -StorageQuota <insert int here>

Anyway, if you're past this now, hope this helps someone else. 
Thanks

**Comment by Sketchdelite** [comment]
Hey mhomol, I'm writing because I encountered the exact same error message and managed to get to a resolution after a couple of months of talks with Microsoft Support

As you had confirmed in your case, the target site that you were trying to register as a hub site had the appropriate storage quota, or at least had a higher quota than your usage. I had checked this on my side too.

However, for my case it was not the target site that had reached it's quota limit, but the "https://tourismholdings-my.sharepoint.com" site. The personal sharepoint site for the user you happen to be logged in under.
I didn't bother asking Microsoft Support why this would be the case, but for my personal site, the quota and usage was the same (and so, maximum storage limit reached).
I bumped the quota on this site, tried registering the target site again, and it's working now! I was quite surprised.

Get-SpoSite -Identity "https://<tenant>-my.sharepoint.com" | fl
Set-SpoSite -Identity "https://<tenant>-my.sharepoint.com"  -StorageQuota <insert int here>

Anyway, if you're past this now, hope this helps someone else. 
Thanks

**Comment by jdurlewanger** [comment]
@Sketchdelite  Did you have to wait a certain amount of time before registering the hub site? I am struggling with this issue as well and was trying the suggestion you posted.

**Comment by Sketchdelite** [comment]
@jdurlewanger , It was fairly instant for me, made the change to the service account's personal storage quota, and then within a minute was able to register the hub site.

Just in case, whichever user you're running the powershell commands under, ensure the personal stroage quota is bumped.

**Comment by jdurlewanger** [comment]
> @jdurlewanger , It was fairly instant for me, made the change to the service account's personal storage quota, and then within a minute was able to register the hub site.
> 
> Just in case, whichever user you're running the powershell commands under, ensure the personal stroage quota is bumped.

Unfortunately that did not work for me. I have opened a case with microsoft. I will post what they find.

**Comment by dvselva** [comment]
Hello, All, facing the same issue. @jdurlewanger, Hope you got the solution from MS. can you share it please. Thanks in advance.

**Comment by jdurlewanger** [comment]
Hey @dvselva this was awhile ago and I’m failing to remember what my initial problem was. but I think the solution is to use powershell v7

**Comment by dvselva** [comment]
Hello, Thank you for the quick response. I tried to register the site via Powershell 7 and getting the same error. Register-SPOHubSite : Site has exceeded its maximum file storage limit. I am trying to register a site as hub site and getting this error both in the admin center and also in powershell

**Comment by ShaunGould** [comment]
Was there ever a fix for this? I'm experiencing the same issues currently whereby I'm receiving the error 'This site has exceeded its maximum file storage limit'. This appears to be for any site I attempt to register in the SharePoint Admin centre,

**Comment by dvselva** [comment]
I had to open a support ticket to increase that limit on my site host site collection.
