### ISSUE TITLE
[BUG] Remove-PnPListItem Broken

### ISSUE THREAD

**Issue by JazBInKC** [pnp/powershell#1959]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
The cmdlet fails to run.  The error is:  **Error: The parameter "Force" is declared in parameter-set "Delete single item in list" multiple times.**
### Expected behavior 
Something else

### Actual behavior 
![image](https://user-images.githubusercontent.com/96395010/172983287-1db92bb3-0697-4125-a3e6-48d759256230.png)

### Steps to reproduce behavior
See screenshot

### What is the version of the Cmdlet module you are running?
1.10.42 and .43, PS5.1

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by JazBInKC** [comment]
I believe the issue is the first "Delete single item in list" that should probably be "Delete all items in list"

![image](https://user-images.githubusercontent.com/96395010/172987333-b4720c09-3fc4-4bb0-935f-0f1bc7b90be6.png)

**Comment by KoenZomers** [comment]
I'm afraid its not this easy to fix it. When I test it here, it cannot match the right paramset anymore when using i.e. `Remove-PnPListItem -List "Test" -Identity 1`. It requires me to add `-Force` to it as well. Can't figure out how to fix this due to the large amount of paramsets.

@fowl2 it seems like this issue is introduced since your PR on this code. Would you mind having a look at this cmdlet to see how it can be fixed?

**Comment by heinrich-ulbricht** [comment]
Ha, ran into this as well while debugging #1949

**Comment by KoenZomers** [comment]
Thanks for sharing your view here @heinrich-ulbricht. I also spent more than an hour on this one and couldn't figure it out. It seems like with all the paramsets there are now, PowerShell cannot find the right one anymore. Tried various ways of fixing it, but it seems to hold on to the wrong paramset. I ran out of options and ideas on how this can be fixed myself. I believe it could be due to that this single cmdlet is trying to deal with too many scenarios. And I believe that's what SINGLE_List and SINGLE_ListItem are also for: one tries to deal with the scenario where you pass in a list and a list item, i.e. by its listitem id. The other where you pass in a listitem instance, which already has a parent list so you don't need to pass in the list as well.

Any other views, thoughts are appreciated for this one to try to come up with a solution.

**Comment by KoenZomers** [comment]
@JazBInKC can't you just switch back to the latest stable release to get the job done for now?

**Comment by JazBInKC** [comment]
@KoenZomers - I suppose I could, if I knew what that was.  I discovered the issue while running a newly created script under 1.10.42.   If I go back too far, I'm running the risk of fixed cmdlets reverting to their former wonky status.  I don't suppose @fowl2 (last person to update the code?) could provide some relief?  As always, your help appreciated.

**Comment by fowl2** [comment]
I've posted a PR https://github.com/pnp/powershell/pull/1984 that should fix this. 

`Get-Command -Syntax Remove-PnPListItem` (mentioned in [about_parameter_sets](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parameter_sets?view=powershell-7.2#:~:text=Use%20Get%2DCommand%20%2DSyntax)) was very helpful in visualizing where the problem was.

**Comment by KoenZomers** [comment]
@fowl2 thanks for your efforts!
@JazBInKC the code has been merged. Can you try it again with the nightly of tomorrow to see if all works well for you?

**Comment by JazBInKC** [comment]
@KoenZomers @fowl2  - Great news.  I will update with the next nightly revision and test it.  Thanks!

**Comment by JazBInKC** [comment]
@KoenZomers @fowl2 - installed 1.10.50 and tested.  The cmdlet is fixed.  Thank you!

**Comment by KoenZomers** [comment]
Thanks for testing and confirming @JazBInKC
