### ISSUE TITLE
MissingMethodException calling Get-PnPWebPart (SP2016 OnPrem)

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/powershell#196]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? No.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** No.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Missing Method Exception

### Expected behavior 
Diplsay Webparts

### Actual behavior 
get-pnpwebpart : Method not found: 'System.String Microsoft.SharePoint.Client.WebParts.WebPartDefinition.get_ZoneId()'.
At line:1 char:1
+ get-pnpwebpart

### Steps to reproduce behavior
Get-PnPWebPart -ServerRelativePageUrl "/sites/demo/sitepages/home.aspx"

### What is the version of the Cmdlet module you are running?
Microsoft.SharePoint2016.CSOM  16.0.4690.1000
Install-Module SharePointPnPPowerShell2016

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

**Comment by erwinvanhunen** [comment]
Are you by any change running this -on- the server? Or from a remote machine? It sounds like PnP PowerShell is using a different version (e.g. older) of CSOM.

**Comment by FullStackRafik** [comment]
Hello,
Thanks for your prompt reply.
This is from a remote machine.

**Comment by FullStackRafik** [comment]
FYI:
PS C:\WINDOWS\system32> Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

Name                        Version
----                        -------
SharePointPnPPowerShell2016 3.29.2101.0

**Comment by erwinvanhunen** [comment]
Can you run this PowerShell snippet?

```powershell
[AppDomain]::CurrentDomain.GetAssemblies() | ?{$_.Location -like "*Microsoft.SharePoint.Client.dll"} | %{Get-Item  $_.Location | select -ExpandProperty VersionInfo}
```

It should return one entry, and show a file version and product version stating: 16.0.4690.1000.

**Comment by FullStackRafik** [comment]
Yes, her is the result:
ProductVersion   FileVersion      FileName
--------------   -----------      --------
16.0.4321.1000   16.0.4321.1000   C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.SharePoint.Client\v4.0_16.0.0...

**Comment by erwinvanhunen** [comment]
Also: is the page you're trying to access a modern page or a classic webpart page?

**Comment by FullStackRafik** [comment]
It's a classic webpart page.

**Comment by FullStackRafik** [comment]
I have the same issue using SP2019 intranet.

**Comment by erwinvanhunen** [comment]
Okay, so the version number I posted is the one we include with the PnP PowerShell installation, but it seems there is some other tool running on your computer that actually loads/uses an older version. That's the reason you see the error message. It's a limitation of PowerShell (nothing specific to PnP PowerShell) that only one version of an assembly can be loaded at the same time. The one that is loaded in your case is older and causes the issue, as we require a newer version. 

So in short: something else is installed on your computer that uses an older version. A typical reason for this is that the application installed the older version in the Global Assembly Cache. Assemblies in the GAC always 'win' over locally available ones. E.g. if a program finds a version in the GAC it will use that one, even if it is also available in the same folder of the application. In your case you see that the path listed is pointing to the GAC.

A typical 'offender' of this problem is Visual Studio if you have the SharePoint development extensions installed. They took the liberty to assume that you only want one version of the CSOM assemblies on your machine, which is usually not the case...

There is unfortunately nothing we can do about this, other than you check if there is an updated version available for Visual Studio (-if- you have Visual Studio installed)

**Comment by FullStackRafik** [comment]
I have the latest Nuget package installed with Visual Studio: 16.0.4690.1000

**Comment by FullStackRafik** [comment]
I've also check on GAC there is nothing!

**Comment by erwinvanhunen** [comment]
The path returned by the ps snippet you ran says something different though:

```
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.SharePoint.Client\v4.0_16.0.0...
```

That's pointing straight to the GAC on your machine.

**Comment by FullStackRafik** [comment]
Yes, I agree with you.
But do you think that this issue is related to this SPClientDLL's version?

**Comment by erwinvanhunen** [comment]
Very likely. The ZoneId property has been introduced in a later version of the Microsoft.SharePoint.Client.dll assembly, it wasn't available from day one however the SharePoint extensions for Visual Studio are not very often updated and most likely run an older version. An easy test could be to try it on a computer (or virtual machine) which does not have Visual Studio installed.
