### ISSUE TITLE
[FEATURE] Get-PnPTeamsChannelUser to return the UPN

### ISSUE THREAD

**Issue by Rbubbles** [pnp/powershell#1999]
Is your feature request related to a problem? Please describe.
The request is to be able to retrieve the Team Channel users UPN

Describe the solution you'd like
Get-PnPTeamsChannelUser -Team "My Team" -Channel "My Channel"

Describe alternatives you've considered
Something similar to Get-PnPTeamsUser, which returns the UPN's
Currently Get-PnPTeamsChannelUser returns:
![image](https://user-images.githubusercontent.com/100543772/174190353-a582595b-c0a2-42f2-b763-55f790ffdd42.png)

Additional context
As a global or Teams admin in my organization, i require the ability to retrieve the UPN of a Channel User

**Comment by svermaak** [comment]
+UpVote

**Comment by gautamdsheth** [comment]
Hi, thanks for raising this feature request.
Unfortunately, this is not possible unfortunately due to Graph API limitations.

We are using this API underneath:

https://docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&tabs=http

Unfortunately, it doesn't return the UPN value.
But you can use the userId value to get the UPN like below:

`Get-PnPAzureADUser -Identity 328c7693-5524-44ac-a946-73e02d6b0f98`
