### ISSUE TITLE
[FEATURE] Azure Cloud Shell integration

### ISSUE THREAD

**Issue by edyoung** [pnp/powershell#21]
**Is your feature request related to a problem? Please describe.**
Since Azure Cloud Shell ships the PNP m365 CLI by default, we'd love to include the PNP PowerShell module too. (I'm the engineering manager for Cloud Shell.) Ideally this would also include supporting the implicit authentication that Cloud Shell enables via exposing a Managed Identity endpoint which can provide oauth tokens based on the logged-in user's credentials.

**Describe the solution you'd like**
Submit a PR to github.com/Azure/CloudShell which adds this module to the list of preinstalled PowerShell modules. It would probably make most sense to do this when the module is no longer considered preview.

In case of questions feel free to ask!

**Comment by erwinvanhunen** [comment]
The moment we go with GA I'll create a PR on the cloudshell repo.

**Comment by JustinGrote** [comment]
`Connect-PNPOnline -ManagedIdentity` currently doesn't work in cloud shell in my testing currently, the context doesn't exist. That should be fixed, and then some cloud shell detection logic should be added (`ENV:ACC_VERSION` can be used) so that connect-pnponline just works by entering the uri.
`connect-pnponline -url https://mytenant.sharepoint.com -PnPManagementShell` works

There should also be guidance for users who haven't approved the app yet, because currently the linux logic uses bash `xclip` which doesn't exist in cloud shell so it throws an error on register-pnpmanagementshellaccess

**Comment by erwinvanhunen** [comment]
The current implementation of the built-in service using in the cloud shell does not allow us to acquire an access token for a SharePoint tenant, resulting in us not being able to create a context. Unless that is fixed on their end, the actual added value of -ManagedIdentity is rather low. We can acquire an accesstoken for the graph, and all graph based cmdlets (Teams/Planner/Microsoft 365 groups) cmdlets should work.

Regarding the Register-PnPManagementShellAccess cmdlet: that has been fixed and that fix is available since 0.3.10-nightly.
