### ISSUE TITLE
[FEATURE] PNP needs to have automatic retry options on all cmdlets

### ISSUE THREAD

**Issue by iloving** [pnp/powershell#2274]
**Is your feature request related to a problem? Please describe.**
I have been trying to use PnP to automate the configuration of our sharepoint sites.  The process has been impacted horrendously by the sheer unreliability of Sharepoint.  It seems like there is a 75% chance that my script will randomly fail because Sharepoint will throw an error for no reason.  Examples include:

- Unknown error thrown when creating a new sharepoint group.
- It randomly can't find a group that absolutely exists
- Cannot find the tenant site
- Cannot find an Azure AD user or group

Not one single command is immune from Sharepoint's shocking levels of instability.  I can run my script, unmodified, 5 times, and three of those times it will fail for a completely different and random reason.

**Describe the solution you'd like**
Every cmdlet needs to attempt an action multiple times before returning an error.

**Describe alternatives you've considered**
I have been forced to set $ErrorActionPreference = "Stop" because I keep getting random failures.
I currently need to wrap every single PnP call in a dedicated loop that checks for failure and retry the command before aborting the script.

**Comment by CallumCrowley** [comment]
@iloving if you are experiencing this level of instability, I would recommend contacting Microsoft Support regarding your tenant (assuming you're using SharePoint Online). I personally haven't seen the level of instability you're seeing and I use many SharePoint tenants every day.

**Comment by iloving** [comment]
I have contacted Microsoft support in the past for other issues, and the quality of support I received was so laughably abysmal that I entirely expect that they will not be capable of helping me.  Microsoft's "engineers" appear to be on par with an average companies tier 1 tech support.  All they do is ask me for screenshots and attempts to reproduce the problem, and then nothing happens.  So far the solution to every problem I have had with Sharepoint has been to wait and see if the problem goes away.

Since this issue is happening so randomly, I am 100% confident that the first thing they are going to say is to to go back to you guys since it's your code I'm using.  I honestly don't know whether the issue is with Sharepoint or PnP.   I'm glad that you're not having any problems but I can tell you not all of us are so lucky.

I ran my script several times last night after I raised this issue, and it didn't fail once.  But when I was using it earlier in the afternoon, I was lucky if my script would run _without_ a failure.

The purpose of my script is to create a sharepoint site and configure it according to our requirements.  Nothing fancy, just a couple of document libraries with specific permissions.  I disable the more advanced functionality in sharepoint so that the site works exclusively as a document repository.  Since I'm running this script repeatedly for testing, I have code that checks for an existing site and deletes it before creating it again.

I just ran it again twice just now.  First time it worked perfectly.  Second time, I got a "User cannot be found" error when trying to use Add-PnPGroupMember.   I will try to pay closer attention but my anecdotal evidence is that the problem gets worse over the course of the afternoon, and then goes away in the evening.

**Comment by CallumCrowley** [comment]
If you feel that the problem is with code in this library then do go ahead and raise individual issues for each problem with environment details and error logs.

If the issue is clearly server side, then I'm not sure here is the right place to complain about it. You would be better off going back to Microsoft support, as they are the only people who can definitively determine what has caused a server side problem (other than obvious throttling error messages).

**Comment by CallumCrowley** [comment]
If you feel that the problem is with code in this library then do go ahead and raise individual issues for each problem with environment details and error logs.

If the issue is clearly server side, then I'm not sure here is the right place to complain about it. You would be better off going back to Microsoft support, as they are the only people who can definitively determine what has caused a server side problem (other than obvious throttling error messages).

One thing to note is that quite often with provisioning, there can be server side delays before something is available in a site but we really do need individual issues to be logged to provide advice.

**Comment by gautamdsheth** [comment]
Each and every cmdlet has a default retry mechanism. We retry them in case of throttling or 503 errors. The default behavior is configured such that all the cmdlets will be retried 10 times in case of throttling or 503 errors. If the error is different, it won't be retried.

Look at your issue with random failures, it is clearly a server side failure and not a throttling issue.

Would suggest that you , as @CallumCrowley mentioned , reach out of MS support for environment instability issues as we wont be able to help.
