### ISSUE TITLE
[BUG] Set-PnPSearchConfiguration: Internal Server Error. Eecuting with search import files that were working 2 weeks ago

### ISSUE THREAD

**Issue by benjacernuda** [pnp/powershell#2310]
### Notice
Hi

I have executed the script to import search managed properties in the Search Schema. We have use the same file 2 weeks ago in different tenants and worked without any problems but now we are getting an Internal Server Error

This happens in all of our tenants.

We are using PnP.PowerShell 1.11.0. Same version 2 weeks ago when this was working

We have tried this workaround but still having the error
https://github.com/pnp/powershell/issues/1328

Thanks for your help 

Ben

### Expected behavior 
The script run without errors and at the end the search managed properties are created in the Search Schema

### Actual behavior 
![image](https://user-images.githubusercontent.com/13738880/188116507-a9ad6f9b-1aa3-4cf1-af8e-70df53dc8338.png)

### Steps to reproduce behavior
Execute et-PnPSearchConfiguration with a import file that was working before

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.11.0.

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @benjacernuda , thanks for raising the issue.
The error is coming from the server side.

Ran into this myself, we raised the issue with Microsoft support.
They acknowledged the issue and will rollout a fix for it.

Got this reply from MS Support.

![image](https://user-images.githubusercontent.com/8832018/188283462-d3f8532c-afee-4acb-8f0c-51b142c3ce23.png)

Will close the issue here as we can't do anything about it here. Will just have to wait for the fix to be rolled out globally. Keep checking for you health center in admin portal for updates.

**Comment by benjacernuda** [comment]
Many thanks Gautam

**Comment by benjacernuda** [comment]
hi @gautamdsheth,

It seems that in all our environments the Search advisory has been fixed (Status: Service Restored Saturday September the 3rd) but we are still getting the same Internal Server Error trying to import search properties using Set-PnPSearchConfiguration. Not sure if you are experiencing the same problem.

Many thanks!

Ben
