### ISSUE TITLE
[Enhancement] Add-PnPPageSection does not support VerticalSectionZoneEmphasis

### ISSUE THREAD

**Issue by navkri789** [pnp/powershell#2350]
### Reporting an Issue or Missing Feature
Missing Feature

### Expected behavior 
Add-PnPPageSection should be able to set the Zone Emphasis of a Vertical Section

### Actual behavior 
No way to currently do it

### Steps to reproduce behavior
Add-PnPPageSection -Page $pageName -SectionTemplate OneColumnVerticalSection -Order 0 -ZoneEmphasis 2 -VerticalSectionZoneEmphasis 1

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by milanholemans** [comment]
Hi @navkri789 

Currently you can set the zone emphasis of the vertical section by using `-ZoneEmphasis`. Both the normal section and the vertical section will get a background color. It is true that you cannot explicitly choose the color of only the vertical section but this is because we are limited by what the CSOM API is offering us.

**Comment by gautamdsheth** [comment]
Closing it as we have merged it via a PR.
It will be available from tomorrow's nightly builds
