### ISSUE TITLE
[FEATURE] - Enable Audience Targeting on List

### ISSUE THREAD

**Issue by pkbullock** [pnp/powershell#2408]
I have recently written code into the PnP Provisioning feature for enabling audience targeting (PnP Framework) on lists and libraries - I believe this may also make sense adding to the Set-PnPList and New-PnPList cmdlets.

I am happy to write the code if you agree? 

What im thinking of doing is within PnP Framework, add the method for setting this in a common way for both libraries that can be used by the PnP PowerShell command - but what I wanted to know, is are there any considerations e.g. coupling between PnP Framework and PowerShell?

**Describe alternatives you've considered**
This will be part of the PnP Provisioning feature so can be set on the XML file.

**Comment by gautamdsheth** [comment]
hi @pkbullock , totally welcome your contribution , looks like a cool feature.

In the PnP Framework, there is an Extensions folder and inside that we have ListExtensions.cs file which contains the extension methods that we use.

![image](https://user-images.githubusercontent.com/8832018/193470210-325586d8-ea16-4ac5-9f70-117c7376cf54.png)

Inside this class, you can add your method for audience targeting. This can be used by both the provisioning engine and PowerShell cmdlets.
Once it is merged there, you can submit the PR here in the New/Set-PnPList cmdlets. 
Don't need to do anything special because PnP PowerShell always takes the latest nightly build of PnP Framework. So, you can simply write code to consume the method you wrote in PnP Framework.

**Comment by pkbullock** [comment]
@gautamdsheth - Brilliant, thank you for the pointer - I am a little rusty lol. Will submit a PR in the coming days... 😊

**Comment by pkbullock** [comment]
Hi 

Can you assign me to this one? 

I've already started to work on it 😃

**Comment by veronicageek** [comment]
@pkbullock - All yours my friend!

**Comment by kbeeveer46** [comment]
@pkbullock Did you end up working on this? The reason I ask is that it appears that audience targeting on Quick Launch links does not work and I thought if you had experience with audience targeting on this ticket you might know what's wrong and how to fix the audience targeting quick launch issue. 

I created an issue on GitHub but they moved it to the Discussions section and I never got a response to it. https://github.com/pnp/powershell/discussions/2392

It appears that the PnP PowerShell code correctly assigns the audiences to the quick launch links but when you view the SharePoint site they have no effect. If you run the PowerShell code and then go to the site and manually edit the menu by changing the title of a menu item, for example, and click save the audiences all the sudden work. Without re-triggering the "save" command via the Save button in the SharePoint UI, the audiences applied via PnP PowerShell do not work. 

I've tried several "hacks" like changing a menu item's title via PowerShell and then changing it back to try and trigger the "save" command but nothing seems to work.

**Comment by gautamdsheth** [comment]
hey @pkbullock , any update on this ? Would love to have it added to the cmdlet :) 
If you don't have time, please do let us know, no pressure 😊

**Comment by veronicageek** [comment]
Removing @pkbullock as the assignee.

**Comment by pkbullock** [comment]
Sorry about this :-( will be stepping up contributions soon.

**Comment by gautamdsheth** [comment]
Closing it , as it was merged via the PR.
