### ISSUE TITLE
[BUG] Get-PnPTenantSite - SharingCapability Filtering Does no Work

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#2442]
### Reporting an Issue or Missing Feature
I am reporting a a bug

### Expected behavior 
`Get-PnPTenantSite | where { $_.SharingCapability -ne 'Disabled' }` should return sites with external sharing enabled, However, it seems the search results are messed up.

### Actual behavior 
`Get-PnPTenantSite | where { $_.SharingCapability -ne 'Disabled' }` provide wrong externally sharing count. Many of the sites are not externally shared at all
![image](https://user-images.githubusercontent.com/5260172/194902369-2d7724b8-5227-42da-af6e-ab39583ee4aa.png)

### Steps to reproduce behavior
```
$sites = Get-PnPTenantSite
$extSites = $sites | where { $_.SharingCapability  -ne "Disabled" }
$extSites.Count 
```

Workaround:
```
$sites = Get-PnPTenantSite
$extSites = foreach ( $s in $sites ) {
$site = Get-PnPTenantSite -Url $s.Url
if ( $site.SharingCapability -ne 'Disabled' ) { $site }
}
```

### What is the version of the Cmdlet module you are running?
```
Name: PnP.PowerShell
Version: 1.11.99
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @YuriySamorodov, this is an issue with the `Tenant.GetSitePropertiesFromSharePointByFilters` method/API of the SharePoint CSOM SDK.

We will not be able fix it. 
Request you to please raise the issue with Microsoft via their support channel or premium support.
This requires a server side fix, once Microsft does it at their end, it will be automatically available in PnP PowerShell since always use the latest CSOM SDK. If it is fixed at API level, then we wont have to update as well.

Will close this issue now, thanks for sharing a workaround.

**Comment by YuriySamorodov** [comment]
Opened a ticket with Microsoft: ‎33319163‎

**Comment by GeoffOrlebeck** [comment]
@YuriySamorodov, I also opened a ticket based on this issue and MS support directed me to their SharePoint Feedback Portal. I submitted this request/issue there as well: 

https://feedbackportal.microsoft.com/feedback/idea/92bcc9df-3582-ed11-a81b-6045bdaf6a9e
