### ISSUE TITLE
[BUG] -UpdateType SystemUpdate does not work when updating FileLeafRef

### ISSUE THREAD

**Issue by eeddie13** [pnp/powershell#2478]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Use the following code snippet to update the file names for items in a given library and retain the Modified By and Modified Date metadata.

### Actual behavior 
The file names are being updated as expected however the Modified Date and Modified By are also being updated:
![image](https://user-images.githubusercontent.com/12251965/196409542-a6504025-571d-4be3-9e25-50c18a70d894.png)

### Steps to reproduce behavior
```
Connect-PnPOnline $siteUrl -UseWebLogin
$list = Get-PnPList $libUrl
$items = Get-PnPListItem -List $list -PageSize 5000 | Where-Object {$_.FileSystemObjectType -ne 'Folder'}

foreach($item in $items){
  $newName = "The Updated File Name.docx"
  Set-PnPListItem -List $list -Identity $item['ID'] -Values @{'FileLeafRef'=$newName} -UpdateType SystemUpdate
}
```

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@gautamdsheth FYI - Mentioning #1863 which had an issue with the `-Batch` parameter, but it seems there's maybe a problem even without it.

**Comment by gautamdsheth** [comment]
@veronicageek / @eeddie13  - I tried with pure CSOM as well without PnP. So, the issue lies with the API. Unfortunately, we can't do anything about it.

Please reach out to Microsoft by creating a support ticket, this is not something we can fix as the issue lies at the API layer. Once they fix it, it will be automatically available as we always use the latest SDK code.
