### ISSUE TITLE
[FEATURE] connect-pnponline via proxy

### ISSUE THREAD

**Issue by radoslawcz** [pnp/powershell#25]
**Is your feature request related to a problem? Please describe.**

I am unable to connect to SharePoint Online via a proxy. I want to connect to SPO from a script with using the "Connect-PnPOnline $SiteURL -Credentials $cred" command. There is a proxy set in IE which I want to use when connecting. The only possible way to connect is by using the "-UseWebLogin" option but that only works interactively and I want to run this script from a scheduled task.

**Describe the solution you'd like**

Allow to set a proxy when connecting via the "-credentials" option. For example: Connect-PnPOnline $SiteURL -Credentials $cred -proxy myproxy (or use settings from IE).

**Describe alternatives you've considered**

I searched the Internet and not found a working solution for this. Connecting only works with the "-UseWebLogin" option but it does'nt work when a script is running from a scheduled task.

**Comment by erwinvanhunen** [comment]
If you use the Legacy version, it should follow the default proxy settings of Windows. If you use the new PnP.PowerShell version (multi-platform): -UseWebLogin is not available anymore due to technical changes behind the scenes. However, you can set a proxy by defining an environment variable that points to you proxy server. From https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=netcore-3.1:

* `HTTP_PROXY`: the proxy server used on HTTP requests.
* `HTTPS_PROXY`: the proxy server used on HTTPS requests.
* `ALL_PROXY`: the proxy server used on HTTP and/or HTTPS requests in case HTTP_PROXY and/or HTTPS_PROXY are not defined.
* `NO_PROXY`: a comma-separated list of hostnames that should be excluded from proxying.

On systems where environment variables are case-sensitive, the variable names may be all lowercase or all uppercase. The lowercase names are checked first.

The proxy server may be a hostname or IP address, optionally followed by a colon and port number, or it may be an http URL, optionally including a username and password for proxy authentication. **The URL must be start with http, not https, and cannot include any text after the hostname, IP, or port.**

To set an environment pointing to a proxy server you can do:

```powershell
$env:ALL_PROXY = "http://mylocal.proxy.server:8080"
```

This will set the environment for the current PowerShell session. You can also define it in your system settings, or alternatively in your profile.ps1 for PowerShell (the easiest way to edit that file is by opening PowerShell and executing `notepad $PROFILE`, it will automatically open the file or create it if it doesn't exist). Simple add `$env:ALL_PROXY = "http://yourproxyserver"` to the file.
