### ISSUE TITLE
[BUG] Set-PnPView is not working for Gallery Type View Formatting using Custom JSON

### ISSUE THREAD

**Issue by rbkharade** [pnp/powershell#2514]
### Discussed in https://github.com/pnp/powershell/discussions/2511

<div type='discussions-op-text'>

<sup>Originally posted by **rbkharade** October 28, 2022</sup>
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
Set-PnPView should apply a custom formatting to existing modern SharePoint gallery type view.

### Actual behavior 
I am currently trying to apply a custom Json formatting to existing gallery type view. I first connect to my SharePoint site with Connect-PnPOnline (Tried Interactive, WebLogin , Default & App-only tokens approach). After running Set-PnPView with custom Json, command is getting executed successfully. But not able to get desired formatted view.

### Steps to reproduce behavior
$JSONFormat = @"
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/tile-formatting.schema.json",
  "formatter": {
    "children": [
      {
        "elmType": "div",
        "style": {
          "border-radius": "2px",
          "box-shadow": "0px 1.6px 3.6px 0 #00000024, 0px 0.3px 0.9px 0 #00000024",
          "font-weight": "800",
          "height": "92%",
          "overflow": "hidden",
          "padding-left": "16px",
          "padding-top": "16px",
          "width": "95%"
        },
        "txtContent": "[$Title]"
      }
    ],
    "elmType": "div"
  },
  "height": "250",
  "width": "350"
}
"@
  
Try
{
    #Connect to site
    Connect-PnPOnline -URL $SiteURL -UseWebLogin
    #Set the View Formatting
    Set-PnPView -List $ListName -Identity $ViewName -Values @{"CustomFormatter" =$JSONFormat.ToString()}
    Write-host "View Format Applied Successfully!" -foregroundcolor Green
}
Catch {
    write-host "Error: $($_.Exception.Message)" -foregroundcolor Red
}

### What is the version of the Cmdlet module you are running?
PnP.PowerShell - 1.11.0     

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows</div>

**Comment by rbkharade** [comment]
I have checked the JSON for formatting issues . The JSON looks fine. I have applied the same JSON file manually & it is working correctly.
You can test the same by following simple steps -

Creating a simple SharePoint list with default column Title .
Create a Gallery view.
Select view created in step 2 . Select Format Current View & copy paste above JSON file. It will apply the formatting.
But when tried to do the same thing using PnP PowerShell formatting is not getting applied.

**Comment by gautamdsheth** [comment]
As I mentioned earlier, this not an issue with the cmdlet.

The issue might lie with the encoding or way the string is created/passed.
Please read the links mentioned there and try it that way. 
In the cmdlet itself, we simply expect a string, so maybe the string that you are passing is not correctly formed or something else.

```
Set-PnPView -List "MyList" -Identity "TilesView" -Values @{CustomFormatter = @'
{"schema":"https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json","additionalRowClass": "=if([$DueDate] &lt;= @now, 'sp-field-severity--severeWarning', '')"}
'@
}
```

The above code works at my end, so maybe you can modify your code accordingly and try, check the less than equal to sign for example, it is `&lt;=`, so maybe you need to add some encoding there ? 
Will close this issue here and if you want we can discuss it in the discussion forum.

**Comment by Benj159** [comment]
I have found a solution for the problem and I'm adding it here because I couldn't find anything about this anywhere:

To set the JSON for a **gallery view**, the JSON needs to be wrapped in `{"tileProps":}`

Using the example above it would look like this:
```powershell
Set-PnPView -List "MyList" -Identity "TilesView" -Values @{CustomFormatter = @'
{"tileProps":{"schema":"https://developer.microsoft.com/json-schemas/sp/view-formatting.schema.json","additionalRowClass": "=if([$DueDate] &lt;= @now, 'sp-field-severity--severeWarning', '')"}}
'@
}
``` 
I had to extract this information from the `(Get-PnPView -List $ListName -Identity $ViewName -Includes ListViewXml).ListViewXml` and couldn't find it documented anywhere.
