### ISSUE TITLE
[BUG] Copy-PnPItemProxy documentation

### ISSUE THREAD

**Issue by PowershellScripts** [pnp/powershell#2584]
### Reporting an Issue or Missing Feature
The cmdlet is called **Copy-ItemProxy** (v 1.11.88-nightly) and I cannot find it in 1.12.19. However, there exists a published doc file under https://pnp.github.io/powershell/cmdlets/Copy-PnPItemProxy.html (**with PnP prefix**) with a lot of elements missing. There is no documentation for Copy-ItemProxy.
I could update the .md, but I cannot locate the file in the repository. Neither under Copy-PnPItemProxy.md, Copy-ItemProxy.md, or anything with 'proxy'. 

### Expected behavior 
A documentation page if the cmdlet should exist. Should the cmdlet exist?

### Actual behavior 
Possibly an old doc got published and it doesn't vanish with updates.

### Steps to reproduce behavior
Open https://pnp.github.io/powershell/cmdlets/Copy-PnPItemProxy.html

### What is the version of the Cmdlet module you are running?
1.11.88-nightly
1.12.19

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @PowershellScripts , thanks for raising this.
Have added the docs for this, will be available from tomorrow.

The cmdlet is just an alias of the natively available Copy-Item cmdlet. Added it in here so that it is easier for folks to move files around in the local file system.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-7.3
