### ISSUE TITLE
[FEATURE] Add delay option to Invoke-PnPQuery

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/powershell#2661]
**Describe the solution you'd like**

It would be interesting to have the `delay` option provided by the `ExecuteQueryRetry` method used in backend of the command.

This option was available in the older version of PnPPowerShell. Maybe there's a specific reason why it hasn't been migrated?

**Comment by gautamdsheth** [comment]
Hi @michaelmaillot , we use the `retry-after` header, by default, in case of throttling.

https://learn.microsoft.com/en-us/graph/throttling#best-practices-to-handle-throttling

If the `retry-after` header is not available, then we fallback to a delay which is 500ms with exponential increase. That's why the delay was removed :) 

The newer PnP Framework doesn't expose the delay option either AFAIK.

**Comment by michaelmaillot** [comment]
I didn't know about this header option included to avoid throttling, that's great indeed!

But I was thinking about including a retry delay when an update has been applied to a context object, such as a Term Group for example. In that case, sometimes it's not available right now and when we want to get a specific data, we can face an error. Think of this as a "retry-waiting-update-to-apply" thing more than a "throttling-handler" one 🙂 

But my mistake about the `ExecuteQueryRetry` method parameters: looks like I was refering to the PnP-Sites-Core one...

And after having a closer look at the one declared in PnP Framework, it seems that the retry delay is done increasingly even in a non event-throattling context:

https://github.com/pnp/pnpframework/blob/master/src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs#L203

Sorry for the inconvenience, closing the request.
