### ISSUE TITLE
[FEATURE] - Allow enabling/disabling comments on individual SharePoint lists

### ISSUE THREAD

**Issue by ganesh-sanap** [pnp/powershell#2913]
# Is your feature request related to a problem? Please describe

Currently we cannot enable/disable comments on individual SharePoint lists using PnP PowerShell.

# Describe the solution you'd like

Can we enhance `Set-PnPList` cmdlet to support additional parameter (say `-DisableCommenting`) which will allow enabling/disabling comments on individual SharePoint lists?

I would like to contribute to this library for above enhancement request with the help from repository maintainers/existing contributors. Thank you!

# Additional context

Currently this can be done via SharePoint UI:

![image](https://user-images.githubusercontent.com/25476310/226171118-a31b5a8c-78c6-4db5-a8ef-dc670414ba5e.png)

**Reference**: [Enable/Disable the comments for a SharePoint Online/Microsoft List](https://ganeshsanapblogs.wordpress.com/2021/05/23/enable-disable-the-comments-for-a-sharepoint-online-microsoft-list/)

**Comment by veronicageek** [comment]
All yours @ganesh-sanap 👍🏻 Thanks for contributing!

**Comment by ganesh-sanap** [comment]
Thank you @veronicageek. I am trying to setup development environment by following [Setting up your environment](https://github.com/PnP/PnP/wiki/Setting-up-your-environment) but I am facing below error while running these commands:

```
git remote add --track dev upstream https://github.com/officedev/pnp
git fetch upstream
```

**Error**: 
![image](https://user-images.githubusercontent.com/25476310/226248767-758f0cdf-2768-42f2-b6a4-8129cb587143.png)

Can you please help me with this?

**Comment by veronicageek** [comment]
@ganesh-sanap - This page is for the old repo (now archived).
Hopefully @gautamdsheth or @KoenZomers might be able to help?

**Comment by KoenZomers** [comment]
Thanks for your willingness to contribute @ganesh-sanap!

Have you read up on the steps in this article to get started:
https://github.com/pnp/powershell/blob/dev/CONTRIBUTING.md

I realize there might be some outdated parts in it, but it should give the idea. Feel free to flag parts you get stuck with or need updating.

From a high level, what you would need to do is fork off from this repository by clicking on Fork on the very top right on this page. Create your own fork through the page that will show, if you don't have one yet.

<img width="91" alt="image" src="https://user-images.githubusercontent.com/5940670/226308202-d791f3ff-fc35-4b9e-86fe-60f13b49040a.png">

If you do have a fork already, go into it and ensure its up to date with our dev branch. It will show once you are in your fork in the status bar near to the top:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/5940670/226308373-a819c1f7-4b84-4043-a328-58124989124f.png">

Use the "Sync fork" button to sync your fork if its showing you're X comments behind.

After your fork is in sync, click on the green "Code" button and copy the URL that it shows pointing to your fork.

<img width="236" alt="image" src="https://user-images.githubusercontent.com/5940670/226308663-e0509220-78a4-4964-a23c-cf579126043a.png">

Open up a PowerShell/Command console on your machine and if you haven't already, but it seems you have from your screenshot, download and install the Git tools applicable for your working environment from: https://git-scm.com/downloads . Just do a next-next-finish installation disregarding the countless options it offers in the process. Ensure you open a new console after installing it as otherwise the new path variables will not be in place yet.

In the console go to a new folder where you want to download to the code to and execute:

git clone <URL copied from the step above under the code button>

This will download the code into a subfolder named after your fork. You can start coding from there using Visual Studio Code or the full Visual Studio, whichever you prefer. I use Visual Studio Code myself.

Be sure to create a new branch for the changes you do. Don't do them in your dev branch. Once done with your changes, commit them, push the new branch to your repository, go to GitHub and it will show a bar asking you if you want to create a PR based from your new branch. Click on the button, go through the steps and you should be done.

**Comment by KoenZomers** [comment]
I've taken the time to update the documentation around contributing to outline step by step what you will need to do. Its still under review at the moment, but you can already access and use it here:

https://github.com/pnp/powershell/blob/677a59ea455170488d7a6eb6bb969e303b2a6b8b/pages/articles/gettingstartedcontributing.md

**Comment by ganesh-sanap** [comment]
@KoenZomers Thank you very much for this guide. I will follow the steps mentioned in the contribution guidance.

**Comment by ganesh-sanap** [comment]
Raised new PR #2939. Many thanks @KoenZomers for detailed contribution guide. Please help with updating changelogs/docs if I missed anything!

**Comment by KoenZomers** [comment]
Looks great @ganesh-sanap ! Thanks for your contribution. Keep them coming! :)

**Comment by gautamdsheth** [comment]
Closing this, since its merged !
