### ISSUE TITLE
[BUG] PnP 2.* not working with Az-Module

### ISSUE THREAD

**Issue by HeKr09** [pnp/powershell#3002]
### Reporting an Issue or Missing Feature
I am trying to run PnP and Azure in one PowerShell and receive an error.

### Expected behavior 
Both cmdlets should work

### Actual behavior 
I receive an error when I want to get an azure resource group after connecting with PnP.
![Error](https://user-images.githubusercontent.com/43664126/231197275-c9b7e143-9944-449e-94a3-94d4fc4184ac.PNG)

### Steps to reproduce behavior
```
Connect-PnPOnline -Url $WebUrl -Credentials $Credentials
Connect-AzAccount -Tenant "SOMEID" -Credential $Credentials | Out-Null
Connect-MgGraph -TenantId "SOMEID" -Scopes Group.ReadWrite.All | Out-Null

$AzureResourceGroupName = "SPW_RG"

# Removing Azure resource group
$resource = Get-AzResourceGroup -Name $AzureResourceGroupName

Disconnect-MgGraph
Disconnect-AzAccount
Disconnect-PnPOnline
```

### What is the version of the Cmdlet module you are running?
- Az: 9.4.0
- Az.Resources: 6.5.2
- PnP: 2.1.1 (also tested with 2.0.6-nightly) - but worked everything with 1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
@HeKr09 - We did bump quite a lot of our underlying dependencies in the 2.1.1 update, so that might cause issues with other modules we have no control over. MSGraph and Az modules may be updating / upgrading their dependencies later on, but we would suggest running the PnP cmdlets in a different thread:

https://pnp.github.io/powershell/articles/azurefunctions.html

Moving to a discussion as it's unlikely we can do anything.
