### ISSUE TITLE
[BUG]  Get-PnPTenantSite is intermittently returning 0 sites if number of sites > 5k 

### ISSUE THREAD

**Issue by rajarshibhargav** [pnp/powershell#3175]
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting
Get-PnPTenantSite is intermittently returning 0 sites if number of sites > 5k
### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets
Get-PnPTenantSite should return all Sharepoint sites reliably.
### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.
We have observed that Get-PnPTenantSite is intermittently returning 0 sites  if the number of sites is greater than 5k. We have observed this erroneous behaviour roughly once every 24 hours for 3 organisations. 
### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
Run Get-PnPTenantSite multiple times for an organisation having more than 5k sites. This command should be run repeatedly in a for loop to reproduce this intermittent behaviour.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

Manifest   2.1.1                 PnP.PowerShell 

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Looks like it is a backend server side issue since it happens intermittently. 
The cmdlet itself is not a problem.
We can't do much from our side in this case.

If it is major problem, would request you to raise a ticket with Microsoft support.

If you do raise a ticket with them, don't mention PnP, you should mention CSOM. You can find the source code here for a minimal repro:

https://github.com/pnp/powershell/blob/dev/src/Commands/Admin/GetTenantSite.cs
