### ISSUE TITLE
[BUG] UseWebLogin Connect method is unstable

### ISSUE THREAD

**Issue by SjoerdV** [pnp/powershell#325]
### Reporting an Issue or Missing Feature
I am trying to switch from SharePointPnPPowerShellOnline to PnP.PowerShell while using only the most basic Connect features (so no Graph or AAD, the Interactive method is also not an option).
This exact line:
`Connect-PnPOnline -Url $siteurl -UseWebLogin -WarningAction SilentlyContinue -ErrorAction Stop`

works fine in SharePointPnPPowerShellOnline but returns an error in PnP.PowerShell, just after the popup and me selecting an already logged in account:
`2021-02-23 19:02:48     Error connecting to https://tenant.sharepoint.com/sites/mysite, unable to set additional context sensitive properties: The remote server returned an error: (400) Bad Request.`

- SharePointPnPPowerShellOnline is uninstalled completely, 
- PnP.PowerShell is installed scoped to the current user
- Running on a Non-domain joined pc (workgroup)
- account used is MFA enabled
- having multiple (3) logged on accounts in the IE embedded popup window

### Expected behavior 
I expect a successful connection

### Actual behavior 
I get a 400 error with 'unable to set additional context sensitive properties' message. 

### Steps to reproduce behavior
The line mentioned is actually a fallback so it will be running in the catch statement of some other connect function, but I doubt it would matter. The same error occurs just running the mentioned line plainly.
As a sidenote: sometimes the popup will hang for 5 minutes before showing an error 'Navigation to the webpage was cancelled', but that's only annoying, not blocking. Then after closing all terminals and restarting pwsh and running:
`Connect-PnPOnline -Url https://tenant.sharepoint.com/sites/mysite -UseWebLogin -ForceAuthentication -WarningAction SilentlyContinue -ErrorAction Stop` using **ForceAuthentication** and instantiating a variable with a string for the URL parameter it WILL actually connect... the first time, subsequent connections also fail, or produce a non-responsive popup.... So I am forced to keep using the SharePointPnPPowerShellOnline (for at least one customer) sadly, until this is more stable.

I have read #170 with interest, but since that one is closed, I decided to make a new issue, hoping it would remain a priority to stabilize the -UseWebLogin option.

### What is the version of the Cmdlet module you are running?
1.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
We are awaret's unstable, and this is the reason we only very hesitantly reintroduced it. Initially it was removed from the new PnP PowerShell for this exact reason. We will not put much more effort in maintaining this functionality due to the very 'flaky' premise it's built upon (authenticating in a browser, where we extract the authentication cookies and then use those cookies to call SharePoint behind the scenes with every cmdlet execution). 

We have a stable alternative: `-Interactive`. By default this auth method launches a similar webbrowser popup, but you can even decide to run the whole auth flow in a normal browser: `-Interactive -LaunchBrowser`. It -does- require you to first register either the PnP Management Shell multi-tenant Azure AD app in your tenant (`Register-PnPManagementShellAccess`) or create your own Azure AD App registration (in that case you also provide the `-ClientId [id]` parameter on Connect-PnPOnline, together with `-Interactive`).

E.g. 

```powershell
Register-PnPManagementShellAccess
```

If you are not an administrator that allows you to consent to an application, simply sent your administrator to this url:

```
https://login.microsoftonline.com/contoso.onmicrosoft.com/adminconsent?client_id=31359c7f-bd7e-475c-
 86db-fdb8c937548e
```

Replace `contoso.onmicrosoft.com` with your own domain. The admin might ask why so many permissions are being requested, but you can highlight that it's delegate access only. This means that if the user has no permissions, the app will also not have the permissions.

**Comment by SjoerdV** [comment]
I think the 'create your own Azure AD App registration' option might be the best way for my case. Can we just follow this:
https://pnp.github.io/powershell/articles/authentication.html#register-your-own-azure-ad-app
without the 'AzureEnvironment' parameter? And we need to have the Certificate/Thumbprint available in the local certificate store right?

The other 'multi-tenant app' option generates these discussions (even when it's only delegating credentials) with some big companies, if you have an answer for those, I will surely put it up for discussion again:
- "Ah, a multi-tenant app... so we do not control that app? Then we can't allow it. Zero-trust, and stuff."
- "Ah, a multi-tenant app... ever heard of 'supply chain tracking / hacking'? No can do."
- "Weren't there issues with the Delegated Scopes, because some SPO API endpoints still require active User Context or at least App Role permissions? So why should we get ourselves in trouble with scopes?"
- "We prefer using the User/Group claims that are already assigned in SPO instead of relying on generic high-level scopes, it feels that those have too much power"

**Comment by gautamdsheth** [comment]
AzureEnvironment is an optional parameter. By default it will point to the commercial M365 cloud. So, yes you can execute that command without AzureEnvironment param. The certificate/thumbprint will be installed in your local cert store. If there is a different store, you can specify that using the `Store` parameter. So, it needs to be available in a certificate store.

**Comment by ToddKlindt** [comment]
@erwinvanhunen , the [Connecting... documentation](https://pnp.github.io/powershell/articles/connecting.html) gives a -UseWegLogin example and there's no mention of -Interactive. Should that be changed? It's also labeled, "Connecting to SharePoint" on the left nav. If it should be updated I'll volunteer to take the first swing at it.

**Comment by erwinvanhunen** [comment]
The certificate -can- be installed into a store by using the -Store parameter, but that is not required. You can have it simply on your file system or even (however, not really recommended for obvious security reasons) as a base64 string that you embed in a script. Only if you specify the -Store option it will be installed in the specified local certificate store, otherwise the files will only be created on the file system. Obviously, if you want to authenticate with a thumbprint on a local machine you will have to add it to a store.

To answer a few of the items you bring up:

"Ah, a multi-tenant app... so we do not control that app? Then we can't allow it. Zero-trust, and stuff."
Yes you do have control over that. Even if the multi tenant app changes its permissions behind the scenes, an administrator will have to (re) consent to those permissions. An Azure AD app cannot magically change it's permissions for a tenant without that consent: changing the permissions on the original app definition will not automatically flow down to tenants using those apps.
Also, it's called an app, but it's mainly a way to ease registration of permissions someone can have and it creates a 'known id' to use for auhentication. Nothing more nothing less. There is no code behind it.

"Ah, a multi-tenant app... ever heard of 'supply chain tracking / hacking'? No can do."
Keep in mind that every SharePoint login effectively uses a multi-tenant app behind the scenes. A pre-approved one even for that tenant (by Microsoft). We have/can have no insights in how you're using the app registration. And because it's only requesting delegate permissions, a (valid to the tenant) user identity is required to successfully acquire a token. See also below for more details.

"Weren't there issues with the Delegated Scopes, because some SPO API endpoints still require active User Context or at least App Role permissions? So why should we get ourselves in trouble with scopes?"
Some of the API endpoints of the Microsoft Rest API or the Graph API do not accept requests by either delegate or app-only permissions. That is true. Nothing we can do about that unfortunately other than highlight this to Microsoft. The limitation is mainly on the app-only side, as some of the APIs require a user identity to work. The 'old'/'legacy' authentication used in SharePoint is already removed of parts of the CSOM APIs. OAuth2 is the only way we have nowadays for auth. We do however make sure that we check the permissions scopes required and if the token is of the correct type. E.g. with the current set of PowerShell cmdlets available in PnP PowerShell there are no limitations. Unless you want to venture off in 'unsupported territory' e.g. use the access token yourself for requests. We make sure that the PnP Management Shell permissions we request match the functionality of both the PnP CLI for Microsoft 365 and PnP PowerShell.

"We prefer using the User/Group claims that are already assigned in SPO instead of relying on generic high-level scopes, it feels that those have too much power"
You can. That's called delegate and that's the main reason that our Multi Tenant PnP Management Shell app only requests delegate permissions. The local SharePoint permissions still apply. Even if the app registration requires 'Sites.FullControl.All', if you're not actively permitted to access a site, you will not be able to do anything to that site.

If this still doesn't convince your customers, then the only option to go forward is to register your own app, with the appropriate permissions, and have them use that.

**Comment by SjoerdV** [comment]
Wow! That's an excellent read. Thanks for your time on this. I do expect some backlash on your answers on 1 and 2, but I'll manage. Thanks again!
