### ISSUE TITLE
[SECURITY] Possible malicious clones on powershell gallery (confirmation requested)

### ISSUE THREAD

**Issue by lectrode** [pnp/powershell#3400]
Apologies if this is not the right location for potential security issues, let alone ones caused by (what appear to be) third party clones.

This [account](https://www.powershellgallery.com/profiles/sharepointpnp) appears to have a transparent icon for their user profile and has one of the main devs listed as an owner for the modules uploaded (the latter is why I'm creating this issue - apparent association with the main dev gives these packages credibility):

https://i.ibb.co/t8KMQRC/project-owner.png

The account seems to have a number of these clones, each with a significant number of downloads (substantially more than PnP.Powershell in some cases):

https://i.ibb.co/LPbSqgP/sharepointpnp.png

When incorporating "SharePointPnPPowerShellOnline" into a powershell script, any time the module was invoked, there was traffic intended to reach 213.24.76.5:

https://i.ibb.co/K6zNsDX/pnp-whois.png

source: https://whatismyipaddress.com/ip/213.24.76.5

I'm unsure as to why a system in the US would need to go through an ISP in Russia to access a Microsoft service, but I'm mainly wondering if that "sharepointpnp" account is officially tied to this project, as well as whether or not @erwinvanhunen is aware he is listed as an owner on those uploads.

**Comment by erwinvanhunen** [comment]
Hi! The SharePointPnP account is a generic account that we from PnP use as a 'backup' account on the PowerShell gallery entries, as currently the entries there are connected to a personal account (e.g. mine). This is in case something happens to me and other members of the team need to access the entries. I -am- the original publisher of the entries (SharePointPnPPowerShellOnline) which is the version of PnP PowerShell that uses .NET 4. It has indeed a significant higher number of downloads simply because it was available for many more years than the current and newer PnP.PowerShell module (which is build on .NET Core and runs on PowerShell 7 and newer). 

Regarding the IP address it is trying to reach: we have telemetry code in the library, but we do not have any hardcoded IP addresses or even server names in the code that refer to any targets. If you see traffic on your machine towards a suspicious IP address I'm wondering if there is some DNS spoofing on your end going on?

**Comment by lectrode** [comment]
Thank you for the confirmation! Glad to hear those are trusted. I'll have to look more into the routing on my end.
