### ISSUE TITLE
[BUG] New-PnpSite ignores -Lcid parameter when connected using a system assigned managed identity

### ISSUE THREAD

**Issue by PascalAE** [pnp/powershell#3411]
### Reporting an Issue or Missing Feature

I have an Azure Runbook that provisions a site using the command: 

Connect-PnPOnline -Url https://[sitename]-admin.sharepoint.com -ManagedIdentity
New-PnpSite -Type TeamSite -Title $newSiteTitle -Alias $siteAlias -Lcid 1033

Site creation works but -Lcid is ignored (Site should be in English, is German instead). The other parameter values -Type, -Title, -Alias, are taken into account as expected. 

I tried it with the following PnP Versions: 
- 2.2.69-nightly
- 2.2.0
- 2.1.1

Did not work in either of them. 
When connecting as a user to the same site, the creation of new sites works as expected and Lcid is taken into account.

### Expected behavior 
Lcid should be considered and not ignored when using the command New-PnPSite connected using system assigned managed identity.  

### Actual behavior 
Site collection is created successfully but Lcid Parameter is ignored. Other parameters like -Type, -Title, -Alias are properly used for site creation. -Lcid is ignored.
Used the exact same command connected to the site as a user, Lcid worked and was taken into account. 

### Steps to reproduce behavior
- Connect to SharePoint admin site collection (https://[sitename]-admin.sharepoint.com) using a system assigned managed identity (in my case an Azure Automation Runbook that has Sites.ReadWrite.All, Sites.Manage.All, Sites.FullControl.All assigned to it)
- Create site using New-PnpSite -Type TeamSite -Title $newSiteTitle -Alias $siteAlias -Lcid 1033 (If your default tenant language is already English, use another language code to reproduce)

### What is the version of the Cmdlet module you are running?
- 2.2.69-nightly
- 2.2.0
- 2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x] Other : Azure Automation Runbook

**Comment by gautamdsheth** [comment]
hi @PascalAE , this is unfortunately not possible due API limitations.

For app-only, we use Microsoft Graph API to create the modern team site with M365 Group.
For user interactive , we use standard SharePoint API to create the site because App-only is not supported for SharePoint APIs.

The issue with Graph API is that it doesn't expose LCID property , so it will always pick the default tenant language.

We can't do anything from the PnP side , so would suggest that you create a feature request for the Microsoft Graph product team.
Closing this issue now.
