### ISSUE TITLE
[BUG] Enable-PnPPageScheduling doesn't trigger creation of required fields

### ISSUE THREAD

**Issue by PeterFlops** [pnp/powershell#3447]
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

Sorry - not sure if this is a PowerShell or Framework issue so logging here first.

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

Issue

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

When the Page Scheduling feature is turned on, a column named "Publish Start Date" is created in the Site Pages library to store the publish date/time info.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

When using the Enable-PnPPageScheduling cmdlet, the column isn't created.  This also means that the field is missing from the Page Details panel.

![image](https://github.com/pnp/powershell/assets/65122662/508daabd-8260-442e-bd8d-670b8740dec3)
<img width="1265" alt="image" src="https://github.com/pnp/powershell/assets/65122662/168f03ef-dbf9-4ba9-a685-285c7c46d10c">
<img width="1009" alt="image" src="https://github.com/pnp/powershell/assets/65122662/8ffe9600-597c-4056-8a6a-ae8c3cd5693f">

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

1. Have page scheduling disabled
2. Connect to site with "Connect-PnPOnline -url $targetSite -UseWebLogin -ForceAuthentication"
3. Run "Enable-PnPPageScheduling"

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows (PowerShell 7 in VS Code)
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ohaak2** [comment]
Same for me. Also running PnP.PowerShell 2.2.0. 

I've compared the exported site template of two newly created communication site - one with scheduled news publishing enabled and on without. Difference in the template are two additional features (one with scope web and one with scope site) and two new fields '_ScheduledVersion' and '_PublishStartDate' along with their field reference in the site pages library.

Now calling Enable-PnPPageScheduling on the site without scheduled page publishing is activating the web feature 'e87ca965-5e07-4a23-b007-ddd4b5afb9c7' and the site feature '3e2f7031-13c0-40b6-87bd-0af42ac62b8d' just fine. It's also adding the required site fields, but seems to omit setting the fields '_ScheduledVersion' and '_PublishStartDate' to the site pages library.

I've applied the changes manually - so effectively running the following three commands on the site like this:

```powershell
❯ Enable-PnPPageScheduling

❯ Add-PnPField -List 'Site Pages' -Field '_ScheduledVersion'

Title                     InternalName      Id
-----                     ------------      --
Scheduled Publish Version _ScheduledVersion b8f74c00-78dd-4ee1-bd62-411df2ff97d2

❯ Add-PnPField -List 'Site Pages' -Field '_PublishStartDate'

Title              InternalName      Id
-----              ------------      --
Publish Start Date _PublishStartDate 1488b62f-b70f-4f75-a384-7a04fbada949
```

However - even doing this steps manually won't do the trick for me. Scheduled page publishing is still switched off as far as the site's user interace is concerned:

<img width="255" alt="image" src="https://github.com/pnp/powershell/assets/91688676/1cb9bdfe-d0cb-49e3-87db-127142897055">

And unfortunatley it's not just the GUI. Feature is definitely still not working. Something else seems to be missing.

So I guess the provisioning template isn't showing us the whole picture. Otherwise applying the changes mentioned above would do the trick. Template wise both sites are then identical in terms of configuration, but still only the one where I've switched on scheduled page publishing using the SharePoint user interface is acutally doing scheduled page publishing.

While having a one stop command to enable the functionality would be nice I could absolutely live with a more hand made solution for the moment. But with the curical information not even included in the provisioning template I've no idea where else to look for a sufficient approad to solve the issue.
