### ISSUE TITLE
adding -ResourceBehaviorOptions to Set-PnPMicrosoft365Group 

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#3578]
I can see the ResourceBehaviorOptions  had been added to the New-PnPMicrosoft365Group. Would it be possible to add the same option to Set-PnPMicrosoft365Group  as cases where we need to add a lot of new users to the Owner/Member groups are pretty common.

:-)

**Comment by KoenZomers** [comment]
@kasperbolarsen Unfortunatelty this is technically not possible

<img width="446" alt="image" src="https://github.com/pnp/powershell/assets/5940670/beae6304-06c7-4963-aa84-8ac5601f59e3">

Source: https://learn.microsoft.com/en-us/graph/group-set-options#configure-groups

<img width="313" alt="image" src="https://github.com/pnp/powershell/assets/5940670/e582c995-d777-41ad-9309-a9e35a046d6a">

**Comment by kasperbolarsen** [comment]
Darn, I didn't expected that property to be immutable,  not at all actually. 
How about adding it to Add-PnPMicrosoft365Group , that is using New-PnPMicrosoft365Group behind the covers, I guess?

**Comment by gautamdsheth** [comment]
@kasperbolarsen - that's not possible as well , since `Add-PnPMicrosoft365Group ` also basically groupifies a site collection using SharePoint CSOM, [check this method](https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-csom/mt829482(v=office.15)), we don't use Graph there. `New-PnPMicrosoft365Group` does use Graph , so that's where we were able to add it.

Will close it since we can't do anything here :(
