### ISSUE TITLE
[BUG]Get-PnpProperty error referring to Microsoft.SharePoint.Client.ClientObject

### ISSUE THREAD

**Issue by sathya-bhat** [pnp/powershell#360]
### Notice
I am trying out 1,PnP.PowerShell and 'Get-PnPProperty' fails for all the new PnP objects. Is this work in progress or this cmdlet will be deprecated?

### Expected behavior 
Return the property or document that this is not supported.

### Actual behavior 
Get-PnPProperty: Cannot bind parameter 'ClientObject'. Cannot convert the "PnP.PowerShell.Commands.Model.SPOSite" value of type "PnP.PowerShell.Commands.Model.SPOSite" to type "Microsoft.SharePoint.Client.ClientObject".

### Steps to reproduce behavior
$cui = Connect-PnpOnline -url 'https://x.sharepoint.com/sites/test' -ClientId 'xyz' -ClientSecret 'abc' -ReturnConnection 
$ten = Get-PnPTenantSite -Connection $cui -Url 'https://x.sharepoint.com/sites/test' 
Get-PnpProperty -Connection $cui -ClientObject $ten -Property 'Template'

### What is the version of the Cmdlet module you are running?
1.3.14-nightly
### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment]
Due to changes in the underlying API the Get-PnPTenantSite cmdlet is not returning an CSOM object anymore. Resulting that you cannot retrieve specific properties for that object anymore using Get-PnPProperty which requires an object of type ClientObject (basic CSOM object)

If you want to retrieve the template you do not have to do the `Get-PnPProperty` call, (nor do you have to use `-Connection`. The `-Connection` parameter is only required if you need to handle multiple connections to multiple sites at the same time and want to mix and match connections.)

So, simplified:

```powershell
Connect-PnPOnline -Url "https://x.sharepoint.com/sites/test" -ClientId 'xyz' -ClientSecret 'abc'
$site = Get-PnPTenantSite -Url 'https://x.sharepoint.com/sites/test'
$template = $site.Template
```

**Comment by sathya-bhat** [comment]
Thank you.
