### ISSUE TITLE
[BUG] Add-PnPListItemComment : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)

### ISSUE THREAD

**Issue by awdhaan** [pnp/powershell#3709]
When creating a new comment to a listitem,

Add-PnPListItemComment -List $list -Identity '1' -Text $comment -Connection $connection

the following error is thrown:

Add-PnPListItemComment : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)

All parameters contain valid data, including the list, listitem identity, comment text ('Lorm ipsum') and the connection

I have also tried to use Invoke-PnPSPRestMethod to create a new list item comment, but the result is the same:
Invoke-PnPSPRestMethod : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)'.

### Expected behavior 
The cmdlet should actually create the comment for the list item.

### What is the version of the Cmdlet module you are running?
1.12.0 (I'm bound to PS5.1 as the scripts are also including ShareGate cmdlets which are not compatible with PS7.x)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
hi @awdhaan , we will not be fixing this issue since we have moved to .NET 6.
The latest version of PnP PowerShell is 2.3.0 and it runs only on PS 7.2 or later.
Would request you to update to that version which also contains quite a lot of fixes for assembly conflicts.

If possible for your scenario, please try to remove additional scripts which depend on other 3rd party modules and check again.
