### ISSUE TITLE
[FEATURE] Register-PnPManagementShellAccess without graphical console

### ISSUE THREAD

**Issue by cctgteddy** [pnp/powershell#3809]
**Is your feature request related to a problem? Please describe.**
I'm trying to script creation of folders in our Sharepoint document library on a Rocky Linux host which does not have a graphical console.

**Describe the solution you'd like**
A new parameter to open a URL on another host and return a generated token. 

**Describe alternatives you've considered**

**Additional context**

**Comment by gautamdsheth** [comment]
@cctgteddy - closing this because we are not going to be supporting PnP Management shell multi-tenant app from 9th September.

https://pnp.github.io/blog/post/changes-pnp-management-shell-registration/

Would suggest you to use Register-PnPEntraIDApp and use your own Entra ID app. You can use NoPopup parameter to complete the flow in a browser.
