### ISSUE TITLE
[BUG] - Connect-PnPOnline results in a 401 Unauthorized error

### ISSUE THREAD

**Issue by diver7** [pnp/powershell#39]
### Reporting an Issue or Missing Feature
Attempting to connect to a SharePoint site using Connect-PnPOnline in PS 7.0.3 results in a "Connect-PnPOnline: The remote server returned an error: (401) Unauthorized." error.  Using the same credentials with SharePointPnPPowershellOnline v3.26.2010.0 and PS 5.1 works fine.

### Expected behavior 
Executing the following commands will connect to the site

$cred = Get-Credential
Connect-PnPOnline -Url http://[tenant-name].sharepoint.com/sites/Test1 -Credentials $cred

### Actual behavior 
Executing the following commands results in an error

$cred = Get-Credential
Connect-PnPOnline -Url http://[tenant-name].sharepoint.com/sites/Test1 -Credentials $cred
Connect-PnPOnline: The remote server returned an error: (401) Unauthorized.

### Steps to reproduce behavior
$cred = Get-Credential
Connect-PnPOnline -Url http://[tenant-name].sharepoint.com/sites/Test1 -Credentials $cred

### What is the version of the Cmdlet module you are running?
0.2.20
PS 7.0.3

**Comment by erwinvanhunen** [comment]
Just to make sure: did you register the PnP Management Shell Azure AD Application? If not:

Due to changes to the underlying CSOM library, we had to make changes to the way PnP PowerShell authenticates. In the older version of CSOM Microsoft allowed the use of something called SharePointOnline credentials to authenticate. They removed this option and we now have to authenticate using OAuth. There is unfortunately nothing we can change about that. 

To use a name/password combination to authenticate we require an Azure AD app registration to be in place. See https://pnp.github.io/powershell/articles/authentication.html for more information.

**Comment by diver7** [comment]
@erwinvanhunen I ran the command Register-PnPManagementShellAccess and it asked for a SiteUrl. Is that site I'm trying to connect to? Will I have to run this for every site I want to connect to? Sounds like from the documentation it's just registering an Azure AD app which I would think only needs to be done once. 

If it actually worked that might answer my questions but trying to run the command throws this error:

_Register-PnPManagementShellAccess: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'._

Any ideas?

**Comment by csahut** [comment]
Hi,

(sort of) same problem here. I moved to PnP.Powershell because I found no way to make previous version work with Powershell 7 (cf #2595).

I did the consent process for PnpManagementShell, it worked, but when I saw the list of consents that have been granted, I removed it right after. That looked way too much to me.

When you talk about https://pnp.github.io/powershell/articles/authentication.html, do we agree that only the first option is applicable with PnP.Powershell ?

**Comment by diver7** [comment]
I updated to PnP.Powershell version 0.2.23. I was then able to run the Register-PnPManagementShellAccess command. Once that was done was then able to run the Connect-PnPOnline command.

**Comment by Tyler-H** [comment]
Do we need to re-register PnP in Azure each time we update PnP? I recall doing this earlier this year (circa January), but I just tried to connect again after updating PnP from 1.2.0 to 1.5.0 and i get the same 401 issue with a SPO admin account.

**Comment by KoenZomers** [comment]
> Do we need to re-register PnP in Azure each time we update PnP? I recall doing this earlier this year (circa January), but I just tried to connect again after updating PnP from 1.2.0 to 1.5.0 and i get the same 401 issue with a SPO admin account.

Old topic but as I see in the stats people are still frequently visiting this topic, the answer is no: the Azure Active Directory Application Registration is in no way tied to a specific PnP PowerShell version. Register it once and use it with any version of PnP PowerShell onwards.

**Comment by KoenZomers** [comment]
To my experience, there are some specifics you need to configure on your Azure Active Directory Application Registration to get it to work under some circumstances. I.e. if you want to do a Connect-PnPOnline -Interactive using your own application registration, thus also passing in -ClientId, you need to ensure that the Allow public client flows is enabled on the registration, or else it will not work. I'll update our documentation to include this information.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/5940670/153147273-aeeafcb0-6bf1-4d93-92fe-d15be7e3ceda.png">


Easiest way to resolution: just use [Register-PnPManagementShellAccess](https://pnp.github.io/powershell/articles/authentication.html#setting-up-access) to do an application registration automatically and we will ensure all the variables are set correctly for you to use it with PnP PowerShell.
