### ISSUE TITLE
[BUG] Connect-PnPOnline behind firewall error: "Host not reachable" version 2.2.0 and above

### ISSUE THREAD

**Issue by alternone** [pnp/powershell#3908]
### Reporting an Issue or Missing Feature
Issue confirmed by several users. See https://github.com/pnp/powershell/discussions/3151
Related to [Release Release 2.2.0 · pnp/powershell · GitHub](https://github.com/pnp/powershell/releases/tag/v2.2.0)

- Improved Connect-PnPOnline cmdlet to handle ping on the destination server to check if it exists. [PR](https://github.com/pnp/powershell/commit/cc3c5564fca9ce96b1a2ac47c7aabdc8b90136d0) and [#3154](https://github.com/pnp/powershell/pull/3154)

### Expected behavior 
Scripts asks for credentials 

### Actual behavior 
Error by command: Host not reachable

### Steps to reproduce behavior
Simply run command Connect-PnPOnline -Url "contoso.sharepoint.com" behind a firewall. Proxy set. 
Command is working well in 2.1.1 and below.

### What is the version of the Cmdlet module you are running?
From 2.2.0 to latest 2.4.44 nightly

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [X ] Other : official latest Docker image mcr.microsoft.com/powershell

**Comment by gautamdsheth** [comment]
@alternone - sorry for the inconvenience , have fixed it. We will now validate it only if `-ValidateConnection ` parameter is specified. 

Had added this check because we ran into an issue where if you entered incorrect URL, PowerShell itself froze, but looks like that's not happening and is an edge case which we can put behind a parameter.
