### ISSUE TITLE
[BUG] Error Coonect-PnPOnline and Connect-SPOService with credential Parameter

### ISSUE THREAD

**Issue by rohitkumardixit** [pnp/powershell#397]
PS C:\WINDOWS\system32> C:\Users\at84580\Documents\Random Scripts\Delete Folder.ps1
Connect-PnPOnline : The sign-in name or password does not match one in the
Microsoft account system.
At C:\Users\at84580\Documents\Random Scripts\Delete Folder.ps1:2 char:1
+ Connect-PnPOnline -Url 'https://ssecom.sharepoint.com/sites/dev-ardia ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Connect-PnPOnline], IdcrlExce
ption
+ FullyQualifiedErrorId : Microsoft.SharePoint.Client.IdcrlException,Share
PointPnP.PowerShell.Commands.Base.ConnectOnline

**Comment by erwinvanhunen** [comment]
I would not classify directly as a bug as millions of PnP cmdlets are run every day using this connection option.  The error message you see means that the account you use to sign in with does not exist in your environment.

**Comment by rohitkumardixit** [comment]
When I am using with parameter -useweblogin, then no issue.

**Comment by erwinvanhunen** [comment]
Which version of PnP PowerShell are you using? As of version 1.0 of the new cmdlets we use by default Azure OAuth2 authentication. Did you register the PnP Management Shell Azure AD app in your tenant (`Register-PnPManagementShellAccess`) or are you using your own azure ad app for authentication? (`Register-PnPAzureADApp`)

As you say that -UseWebLogin works, that one will ask you to enter the information in a popup. If you provide the credentials with the cmdlet itself, are you 100% sure that those credentials are identical to the ones you enter when using UseWeblogin?  There is a fundamental different on how the authentication works behind the scenes between those two. Instead of using -UseWeblogin, could you try to use `-Interactive` instead? Also notice that the error message is being returned by the server. It's not PnP PowerShell generating this message.

**Comment by rohitkumardixit** [comment]
When connecting to online site we have Microsoft authentication call to our phones and we will enter our pin for authenticating.Then only we can access the site.

But in csom code when conencting to site I am getting the error:

"Exception calling "ExecuteQuery" with "0" argument(s): "The sign-in name or password does not match one in the Microsoft account system.".

**Comment by erwinvanhunen** [comment]
Right. That is correct. If you have MFA enabled on your tenant you will have to use a different way of authenticating. With the legacy PnP PowerShell (e.g. the 'old' version) you have to use -UseWebLogin and enter your credentials. With the new PnP PowerShell you can use -UseWebLogin, however, if possible we recommend you to use '-Interactive' which is a technically better supported option. See https://pnp.github.io/powershell/articles/authentication.html

**Comment by erwinvanhunen** [comment]
Notice that this not a bug, but a limitation of CSOM. CSOM does not allow you to authenticate OOTB when MFA is enabled for a tenant. If you want to run your scripts attended we recommend you to register an Azure AD App and use a clientid and certificate to authenticate towards your environment (basically app-only authentication).
