### ISSUE TITLE
[FEATURE] Add-PnpDocumentSet requires -Folder parameter

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#4022]
**Is your feature request related to a problem? Please describe.**
The file
https://github.com/pnp/powershell/blob/dev/src/Commands/DocumentSets/AddDocumentSet.cs

Uses the root folder of the document library and does not accept a folder as a parameter.

**Describe the solution you'd like**
Add a folder parameter like the add-pnplistitem command.

**Describe alternatives you've considered**
Probably need to manually use the SP client api awkwardly.

**Additional context**
I'm trying to make document sets within folders in a document library.

**Comment by MUNO-Schwan** [comment]
hello, is there a plan to bild that feature in a timeframe ?
I have to create hunders of DocumentSet's  ( DS ) in a Migration and that was more than helpful.
Because the created Document sets have to be Moved to an subfolder structure.
And sorry i also know only the way to create the DS and then copy ot subfolder and delete source  to geht the same result.
Sorry ifi oversee something but i am at the starting point with PNP and sharepointonline! 
So please do the enhancement.
greedings
Norbert

**Comment by gautamdsheth** [comment]
hi @MUNO-Schwan / @SPDEVGUY - have merged the necessary code changes for this. It will be available in tomorrow's nightly builds as well as next major version when we release it.
