### ISSUE TITLE
[BUG]Get-PnPUserProfileProperty

### ISSUE THREAD

**Issue by ttd-kevinclement** [pnp/powershell#4062]
### Reporting an Issue or Missing Feature
Get-PnPUserProfileProperty returning unexpected results in Runbook

### Expected behavior 
Expecting a User Profile Properties PowerShell Object

### Actual behavior 
`System.Collections.Generic.SortedDictionary``2[System.String,System.Object]`

### Steps to reproduce behavior

- Create Runbook with PowerShell 7.2 Runtime
- Import PnP.PowerShell Module
- Execute Runbook with following commands
- `Connect-PnPOnline -Url "xxxxx-admin.sharepoint.com"` -ManagedIdentity
- `Get-PnPUserProfileProperty -Account "xxxx.xxxx@domain.com`

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 2.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ X] Other : Azure Automation Runbook

### Comments
#4061 
This command works as intended in our sandbox tenant, when porting to our corporate tenant it behaves as mentioned above.

**Comment by jackpoz** [comment]
`Get-PnPUserProfileProperty` return type is `SortedDictionary<string, object>` , as you can see at https://github.com/pnp/powershell/blob/ebff896b7978fdc09fee8a71006c8659f1c136b7/src/Commands/UserProfiles/GetUserProfileProperty.cs#L38 and https://github.com/pnp/powershell/blob/ebff896b7978fdc09fee8a71006c8659f1c136b7/src/Commands/UserProfiles/GetUserProfileProperty.cs#L154

It uses the standard PowerShell method [Cmdlet.WriteObject](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet.writeobject?view=powershellsdk-7.4.0)

Here's an example in PowerShell showing the type of the returned object:
![image](https://github.com/pnp/powershell/assets/1153754/11373f94-9b81-40a4-a8a2-3bcf016c7bbc)

Note that Runbooks are different than running scripts on the console as there is no actual console for those scripts to write to. When running scripts on a computer with UI, the output is formatted by PowerShell automatically for that UI context, while runbooks don't.

Here are 2 examples. The first is the default behaviour on PowerShell running on my pc:
![image](https://github.com/pnp/powershell/assets/1153754/9772e022-6eaa-469c-ab32-c9c03ec9f894)

The 2nd has `| Write-Host` which ends up showing the same as you posted:
![image](https://github.com/pnp/powershell/assets/1153754/2d702365-47eb-4aea-8286-b76e17e80e10)

A search suggested to use `.GetEnumerator()`:
![image](https://github.com/pnp/powershell/assets/1153754/80522f26-bb98-46a4-b338-4e802f68f814)

You could try `Out-String` too, not sure if that would still show the type instead of the content.

**Comment by ttd-kevinclement** [comment]
@jackpoz Thank you. Looks like I had not seen this issue before as I had written code to pull properties without seeing the command run on its own previously.
Closing
