### ISSUE TITLE
[BUG] New-PnPTeamsTeam -ResourceBehaviorOptions WelcomeEmailDisabled does not work and throws exception

### ISSUE THREAD

**Issue by zenaidura** [pnp/powershell#4239]
### Reporting an Issue
Issue with New-PnPTeamsTeam -ResourceBehaviorOptions WelcomeEmailDisabled

It complains that the combination is not right.

I am using the following script:
$team = New-PnPTeamsTeam -GroupId $group.Id -Owners $OwnersLogin -Members $MembersLogin -AllowCreatePrivateChannels $false -AllowDeleteChannels $false -AllowCreateUpdateRemoveTabs $false -AllowCreateUpdateRemoveConnectors $false -AllowCreateUpdateChannels $false -ResourceBehaviorOptions WelcomeEmailDisabled

Its not even auto picking the WelcomeEmailDisabled with hitting tab.

### Expected behavior 
It should create a team site when passed with -Group -Owner and/or -Members and not send emails to the members but it sends emails to anyone added as member to the team.

### Actual behavior 
Its throwing error:
Combination of parameters cannot be used together

### What is the version of the Cmdlet module you are running?
2.4.0   PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment]
https://pnp.github.io/powershell/cmdlets/New-PnPTeamsTeam.html documentation shows 2 parameter sets, one "For an existing group" and one "For a new group".
You can see how `GroupId` parameter is only for the existing group case, while `ResourceBehaviorOptions` is only for the new group case:
![image](https://github.com/user-attachments/assets/aad924b9-b603-4ce0-8335-e8fcbb7efd03)

This is because Microsoft Graph supports `ResourceBehaviorOptions` only during the creation of the group as mentioned at https://learn.microsoft.com/en-us/graph/group-set-options#resource-behavior-options

>resourceBehaviorOptions is a string collection that specifies group behaviors for a Microsoft 365 group. These behaviors can be set only on [group creation](https://learn.microsoft.com/en-us/graph/api/group-post-groups).

In your case, if you cannot create the M365 group at that point, you will have to find other changes to change the settings of the existing M365 group, which is usually done on Exchange Online (if I remember correct).

**Comment by gautamdsheth** [comment]
hi @zenaidura , this is by design and not a bug. Those parameters can only be used when you create a new Team. It isn't supported by Graph API on M365 Groups which are to be teamified. This is an API limitation , nothing we can do from our side here.

If you want to set those values, you can use `New-PnPMicrosoft365Group` cmdlet which allows you to set these values and create a new Team as well.
