### ISSUE TITLE
[BUG] Register-PnPEntraIDAppForInteractiveLogin is using an outdated browser

### ISSUE THREAD

**Issue by bartvermeersch** [pnp/powershell#4247]
We are experiencing issues to use Register-PnPEntraIDAppForInteractiveLogin and therefor unable to use PnP anylonger.

Our admin accounts are only allowed to use FIDO2 but the browser you use in the interactive signin flow is not supporting FIDO2.
![image](https://github.com/user-attachments/assets/9548b5f3-e22f-4d4e-98c8-0d3d11bfafa6)

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by bartvermeersch** [comment]
Can you please provide the full details of the app registration that is required so we can create it manually instead?

**Comment by gautamdsheth** [comment]
@bartvermeersch - the old app required too many permissions as mentioned in this blog:

https://pkbullock.com/blog/2024/permissions-for-pnp-management-shell-app

Would advise you to check the scripts and provide them with minimal permissions that you would require for them.

By default, this cmdlet adds the permissions as mentioned below which we believe are required to connect to SP & Graph:

<img width="800" alt="image" src="https://github.com/user-attachments/assets/815b4d97-c381-4a07-ad05-1e819f8ceb6f">

Am working on making this work with device login flow so that it wouldn't open the browser popup.

The command for that would be :
```
Register-PnPEntraIDAppForInteractiveLogin -ApplicationName "testpnp" -Tenant "tenant.onmicrosoft.com" -DeviceLogin -NoPopup
```

This one doesn't work right now due to a bug, will start working with tomorrow's nightly builds.

**Comment by gautamdsheth** [comment]
Also, with the latest builds, you can use `-OSLogin` parameter which supports FIDO and other secure auth modes.

https://pnp.github.io/powershell/articles/authentication.html#authenticating-using-web-account-manager

It does require one additional redirectURI in the client ID as mentioned here:

https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#-oslogin

**Comment by KoenZomers** [comment]
Complete manual steps can be found here. Very easy to set up:
https://pnp.github.io/powershell/articles/registerapplication.html#manually-create-an-app-registration-for-interactive-login

**Comment by bartvermeersch** [comment]
Thank you for the additional info! I don't know why I missed that part of the documentation, probably in the heat of the troubleshooting.
