### ISSUE TITLE
Convert SharePoint On-Premise Publishing Pages to Modern Page - 'Connect-PnPOnline' not working

### ISSUE THREAD

**Issue by gopaltiwari** [pnp/powershell#4405]
Hi,

I am trying to convert On-Premise (SharePoint 2013) Classic Publishing pages to SharePoint online (Modern) pages. I am trying to follow the example given in below article:
[Transform Classic Publishing Pages to Modern Pages using PnP](https://pnp.github.io/script-samples/modernize-classic-pages-from-publishing-sites/README.html?tabs=pnppsv2)

I am getting stuck at the very first step itself when I am trying to get a connection object from SharePoint 2013 on-prem environment:

$sp13Conn = Connect-PnPOnline "<SP2013 On-Prem Site URL>" -Credentials OnPrem -ReturnConnection -TransformationOnPrem

![image](https://github.com/user-attachments/assets/1d8790c1-d056-44cf-85c9-9e06daaef0b1)

I also registered an Entra ID App in Azure to use with PnP by following below articles:
https://pnp.github.io/powershell/articles/registerapplication.html

Still, I am unable to connect to SharePoint 2013 On-Prem environmet using 'Connect-PnPOnline'. 

Environment Details:
I am using latest PnP.PowerShell to execute PowerShell script.
PowerShell version 7.2 (Visual Studio Code)

Any help will be appreciated.

**Comment by KoenZomers** [comment]
PnP PowerShell v2 does not support connecting to an on-premises SharePoint farm. That's why it's failing in your scenario. You will need to use v1.12 of PnP PowerShell. Not sure if that version contains all the functionality you need to make this happen though, but worth a try and your best (and only?) bet for now.

Install in a **PowerShell 5.1** (blue background) session using:
Install-Module PnP.PowerShell -RequiredVersion 1.12
