### ISSUE TITLE
[BUG]  Get-PnPServiceHealthIssue only works when providing a specific Identity

### ISSUE THREAD

**Issue by RyanSCaldwell** [pnp/powershell#4529]
issue: When running Get-PnPServiceHealthIssue, without any parameters, the documentation notes it should return all Health Issues. Instead, the following error is shown:

VERBOSE: Acquiring oAuth token for permission scope ServiceHealth.Read.All
VERBOSE: Access token acquired
Get-PnPServiceHealthIssue: Object reference not set to an instance of an object.

If I run the CMDLET on a specific Identity, it works without issue:

Get-PnPServiceHealthIssue -Identity IT925560 -Verbose
VERBOSE: Acquiring oAuth token for permission scope ServiceHealth.Read.All
VERBOSE: Access token acquired

StartDateTime        : 11/4/2024 8:00:00 PM
EndDateTime          :
LastModifiedDateTime : 11/7/2024 5:01:23 PM
Title                : Users can’t access Intune blogs news and the customer success blog from https://intune.microsoft.com
Id                   : IT925560

### Steps to reproduce behavior
Get-PnPServiceHealthIssue
Get-PnPServiceHealthIssue -Identity IT925560

### What is the version of the Cmdlet module you are running?
2.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by RyanSCaldwell** [comment]
Upgraded from 2.4 --> 2.12 and it's now providing more error information.

WARNING: Failed to parse response from server. Error message: 'The JSON value could not be converted to System.Nullable`1[PnP.PowerShell.Commands.Model.ServiceHealth.Enums.ServiceHealthIssuePostType]. Path: $.value[39].posts[3].postType | LineNumber: 0 | BytePositionInLine: 272354.'.

**Comment by jackpoz** [comment]
Could you please post the output of calling the endpoint defined at https://learn.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&tabs=http#http-request in your tenant ?

The issue is most likely caused by PostType enum not matching the values specified at https://learn.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-1.0#properties .

I created a PR at https://github.com/pnp/powershell/pull/4530 to add the missing enum values.
