### ISSUE TITLE
[BUG] can't use Site.Metadata.CSV sample

### ISSUE THREAD

**Issue by watana2** [pnp/powershell#4564]
Connect-PnPOnline -Url $SPOAdminURL -Interactive -ErrorAction Stop

There was a change in September this year to use app registration, but the script hasn't been updated to reflect the change.

**Comment by jackpoz** [comment]
Hi, could you please include a link to the script you are referring to ? Is it from the PnP Script Samples repository ?

**Comment by gautamdsheth** [comment]
@jackpoz  - its this one - https://github.com/pnp/powershell/tree/dev/samples/Site.Metadata.CSV 

Not sure if we should update it, the whole folder contains some samples, which are quite old. Maybe we move them to script samples ?

**Comment by jackpoz** [comment]
Oh, I never noticed there were samples there. Script samples repo sounds like the best place to store them 😃

**Comment by gautamdsheth** [comment]
hi @watana2 , moving this to a discussion. We wont be working on updating/fixing them due to lack of time and resources. The community can help you from there.

We will be migrating some of these samples to https://pnp.github.io/script-samples/ in the coming weeks.

About your issue , I would double check the SiteID values or maybe update the query filter used in the `Submit-PnPSearchQuery` command.
