### ISSUE TITLE
[FEATURE] Get-PnPTerm from under parent term

### ISSUE THREAD

**Issue by antso77** [pnp/powershell#468]
It would be very useful to have "parent" parameter in Get-PnPTerm command.

Currently I have case, where I create large collection of sites and pages and while doing that, create term for object. But at the moment when I use Get-PnPTerm, it will get labels/ids from whole termset.

For example, there can be multiple terms with label "faq", so without parent information, I cannot check does the label exists already under my site root term, but it will return label from whole termset. At the moment this is hard to achieve and is forcing me to do multiple unnecessary loops to check does term exist under specific parent term.

I'd like to have possibility to check term under parent for example like this:

$subterm = Get-PnPTerm -Identity "faq" -parent "Human recources"  -TermSet "Departments" -TermGroup "Corporate"

Br
Antti

**Comment by gautamdsheth** [comment]
Thanks for requesting this feature. 
Has been merged now, please download the latest nightly releasing tomorrow or wait for 1.5 release which will be happening some time soon :) 
Cheers,
Gautam

**Comment by smchargue** [comment]
> Thanks for requesting this feature. Has been merged now, please download the latest nightly releasing tomorrow or wait for 1.5 release which will be happening some time soon :) Cheers, Gautam

Today is July 8, 2022.  As far as i can tell the current code of PnP.Powershell is v1.11, so there is still no 1.5 mentioned back in March 2021 of this thread. 

I do see that there is currently a seemingly undocumented parameter in Get-PnPTerm named ParentTerm, but it doesn't seem to work as I would have expected.  

example: this command returns "Dallas", as it should 
```powershell
Get-PnPTerm -TermGroup "My Taxonomy" -TermSet "Persona Groups" -Identity "Dallas" -Recursive

Name                           Id                                   Child Terms
----                           --                                   -----------
Dallas                         b96e4df6-b199-4f99-ae26-1c9fbe4ee85b 0 (Not loaded)
```

This command I would expect to also return Dallas, which is a child of Offices, but rather it returns the Parent Term of "Offices", as far as I can tell, -ParentTerm just overrides the -Identity parameter. 
```powershell
Get-PnPTerm -TermGroup "My Taxonomy" -TermSet "Persona Groups" -Identity "Dallas" -Recursive -ParentTerm "Offices"

Name                           Id                                   Child Terms
----                           --                                   -----------
Offices                        d8944c41-a75e-4e3e-b43f-f5dce2e394ac 22 (Not loaded)
```
So, not sure what happened with this feature, or where it is.   But like the original post, I was looking for an easier way to make sure the term I find has the right parent.   i.e. 
```
My Taxonomy | Persona Groups | Offices | Dallas 
``` 
and **not** 
```
My Taxonomy | Persona Groups | Regions | Dallas 
```
I have a workaround, just mentioning this to anyone stumbling in here as I did that I guess this issue is closed but not solved (?)

**Comment by veronicageek** [comment]
@gautamdsheth

**Comment by vojtahanzal** [comment]
Get-PnPTerm : A parameter cannot be found that matches parameter name 'ParentTerm'.

**Comment by gautamdsheth** [comment]
Hi this has now been fixed and it will be available starting from tomorrow's nightly builds as well as next major versions.
Thanks for raising this issue !!

**Comment by shaunpitt** [comment]
Hi there, 

I would like to report that -ParentTerm is not working as expected, based on the documentation. My experience is when using the following code:

`Get-PnPTerm -Identity "Expenditure Approval" -TermSet "TermSet1" -TermGroup "TermGroup1" -ParentTerm "Property" -Recursive`

returns the parent term - "Property"

My term hierarchy is [ TermGroup1 | TermSet1 | Property | Expenditure Approval

Based on the above TermGroup hierarchy I would have expected "Expenditure Approval" as the result.

Also, without using the " -Recursive " option I get the following error.

Get-PnPTerm: Specified argument was out of the range of valid values.
Parameter name: index

Some guidance with this would be much appreciate - thank you

Shaun
