### ISSUE TITLE
[BUG] Connect-PnPOnline Wouldn't Connect using Credentials Method

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#73]
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
This is what I get with SharePointPnPPowerShellOnline 3.26.2010.0
![image](https://user-images.githubusercontent.com/5260172/103321538-2e04c800-4a4b-11eb-8e7b-07c2bb2c49b5.png)

### Actual behavior 
This is what I get when trying to use PnP.PowerShell 0.3.18-nigthly
![image](https://user-images.githubusercontent.com/5260172/103321501-fd249300-4a4a-11eb-9fdd-7c47afa095eb.png)

Error in plain text:
```
Connect-PnPOnline: AADSTS65001: The user or administrator has not consented to use the application with ID '31359c7f-bd7e-475c-86db-fdb8c937548e' named 'PnP Management Shell'. Send an interactive authorization request for this user and resource.
Trace ID: b3e577fa-fd38-42d8-bcbd-d6f387331400
Correlation ID: 50cf494e-409d-443e-b901-1f32725ebc39
Timestamp: 2020-12-29 23:36:40Z
```
Using `Connect-PnPOnline -UseWebLogn` would pop up a web login prompt but pop up window will stuck there showing a white screen
![image](https://user-images.githubusercontent.com/5260172/103321889-df582d80-4a4c-11eb-85c4-0ac3a431e8ef.png)
Please note we have federation enabled.

### Steps to reproduce behavior
```
Install-Module PnP.PowerShell -AllowPrerelease
$credentials = Get-Credential
Connect-PnPOnline -Url https://tenant.sharepoint.com -Credential $credentials
```

```
Connect-PnPOnline -Url https://tenant.sharepoint.com -UseWebLogin
```
### What is the version of the Cmdlet module you are running?
Non-working environment
![image](https://user-images.githubusercontent.com/5260172/103320232-9a7cc880-4a45-11eb-886b-2b86e18a66ce.png)
```
Name    : Get-PnPCustomAction
Source  : pnp.powershell
Version : 0.3.18
```

Working Environment:
![image](https://user-images.githubusercontent.com/5260172/103320084-280be880-4a45-11eb-8a73-1e7d627a5708.png)
```
Name    : Get-PnPCustomAction
Source  : SharePointPnPPowerShellOnline
Version : 3.26.2010.0
```

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by renatoromao** [comment]
Hi @YuriySamorodov ,

Did you try to use the script below?
For me, works well.
Connect-PnPOnline -Url "https://.sharepoint.com/" -PnPManagementShell

Source: https://github.com/pnp/sp-starter-kit/issues/436

**Comment by ToddKlindt** [comment]
You need to run `Register-PnPManagementShellAccess `as a Tenant Admin to create the App Registration in Azure AD. 

If you're only going to access SharePoint you can use `Connect-PnPOnline -Url "https://tenant-admin.sharepoint.com/" -UseWebLogin` to connect. Since it's not using an App Registration you won't be able to manage anything outside of SharePoint like Groups, Teams, AADusers, etc.

**Comment by YuriySamorodov** [comment]
@ToddKlindt , Thanks for the follow up. It appears when I get authentication window stuck at blank when trying to connect with `Connect-PnPOnline -Url $adminUrl -UseWebLogin`

**Comment by erwinvanhunen** [comment]
Does -WebLogin work with the previous version of PnP PowerShell you have been using (e.g. 3.26.2010.0 or newer)? It's exactly the same code we're using, but the underlying framework we're using is different.

Alternatively, try this: 

```powershell
Connect-PnPOnline -Url [yoururl] -UseWebLogin -ForceAuthentication
```
The -ForceAuthentication switch will clear the cookies for that URL.

**Comment by RS-GHub** [comment]
@ToddKlindt ,
I tried to run "Register-PnPManagementShellAccess", which gave me the consent screen and I confirmed the consent for the organisation ( see my comment's to PaoloPia workaround here: https://github.com/pnp/sp-starter-kit/issues/436, where i messed up that part) but then it comes with that screen
![Error consenting Register-PnPManagementShellAccess ](https://user-images.githubusercontent.com/55391170/104600546-0cbdf180-5671-11eb-9776-938f36ea392c.png)

Oh dear - I'm in the middle of implementation of a change and unable to connect with my old code:
Connect-PnPOnline https://xxx-admin.sharepoint.com/

Any advise?
Thanks

**Comment by EnoXirtaMinu** [comment]
I'm having similar issues, having switched from PnP-Powershell to PnP.Powershell on my dev machine.

Connect-PnPOnline -Url $url -Credentials SPOnline 

Does not connect anymore but gives me the 'consent' error, it is just retrieving list items from a list in SPOnline, no management shell access.

Parameters -Useweblogin and  -PnPManagementShell give the error Connect-PnPOnline : Parameter set cannot be resolved using the specified named parameters.

get-command connect-pnponline gives:

CommandType     Name                                               Version    Source                                                                                        
-----------     ----                                               -------    ------                                                                                        
Cmdlet          Connect-PnPOnline                                  1.2.0      PnP.PowerShell

**Comment by erwinvanhunen** [comment]
@EnoXirtaMinu , please create new issues instead of continuing on existing one. It allows us better to keep track of things.

The parameter issue you see means you're missing some required parameters. See the help at https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html for possible combinations.

With the new module, if you want to connect with credentials, you are required to have either the PnP Management Shell application registered or have your own Azure AD App registration. See https://pnp.github.io/powershell/articles/authentication.html for more information about  the authentication changes and approaches.

**Comment by GTEM19889** [comment]
I am having the same issue also. Had a script that took several months to write that is set to run as scheduled task. This worked fine until I recently ran something and was prompted with a message to say I was running a legacy version o PnP PowerShell. Followed the instructions and ran Uninstall-Module followed by Install-Module -Name Pnp.PowerShell
Following this update I get the same error as shown in Original Post. 
What's worse is that I did not initially think that this would have a knock on effect on all scheduled powershell scripts I have built using this. It means over a month worth of data has not been collected because I was busy on another project and did not have time to look into this.
Is there an easy way to downgrade to the previous version?

**Comment by ToddKlindt** [comment]
The best solution is to keep the PnP.PowerShell module and register the Azure AD app so it can connect. Is there any reason that won't work for you?

You can have both modules (PnP.PowerShell and SharePointPnPPowerShellOnline) installed and tell your script or host which one to use. [Here's a blog post ](https://www.toddklindt.com/blog/Lists/Posts/Post.aspx?ID=882)I wrote on how to do it.
In your situation you'll want to add `Import-Module SharePointPnPPowerShellOnline` at the beginning of any scripts that you want to connect the old way. That load does impact the whole host (PowerShell window) so you'll get an error if you do that after PnP.PowerShell has already been loaded in a PowerShell host. If you get an error, just open a new PowerShell window and run `Import-Module SharePointPnPPowerShellOnline` there and run your script.
