### ISSUE TITLE
[BUG]  New-PnPTerm Permission issue

### ISSUE THREAD

**Issue by Grahamworth** [pnp/powershell#895]
### Reporting an Issue or Missing Feature
When running  New-PnPTerm  with an application service registry I get the error:

Command:
![image](https://user-images.githubusercontent.com/13215345/124591423-2ee04180-de54-11eb-9707-8261a3c5add6.png)

Error:
![image](https://user-images.githubusercontent.com/13215345/124591126-da3cc680-de53-11eb-8f1f-75d77822f855.png)

The app registry has the correct permission assigned in Azure:
![image](https://user-images.githubusercontent.com/13215345/124591224-f93b5880-de53-11eb-9993-0bd000321d5e.png)

Using "Get-PnPTerm" work as expected using the app registry
Using weblogin auth works fine as well with both commands. 

### What is the version of the Cmdlet module you are running?
I am running 1.6.0 version of pnp.powershell

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment]
Looks like you are on a old tenant.

Can you please try the workaround mentioned in this blog - 

https://www.techmikael.com/2018/08/modifying-terms-using-app-only-tokens.html 

Basically, you need to add `app@sharepoint` user as term store admin via the old interface. After that, it will start working.

Unfortunately, we cant do anything because its an issue from AzureAD side of the things, so will have to close the issue.
