### ISSUE TITLE
move-pnpfile leaves folders and OneNote Notebooks behind

### ISSUE THREAD

**Issue by virtuetechrocklin** [pnp/powershell#939]
I've been working on a project to re-arrange a clients folder structure in O365 Sharepoint. I've been using move-pnpfile. Overall it works great for smaller folders i.e. sub 100mb. Above that it tends to leave empty folders behind on the -sourceURL. It also leaves OneNote Notebooks behind in the -SourceURL and they don't get moved to the -TargetURL pretty much regardless of the folder storage size.

**Comment by virtuetechrocklin** [comment]
Here's an example of how I've been using move-pnpfile

`Move-PnPFile -SourceUrl “city/Shared Documents/folder1” -TargetUrl "/sites/PrivateCloud/Projects”`

**Comment by veronicageek** [comment]
@virtuetechrocklin - When creating an issue, DO NOT delete the template. Please fill the below:

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment]
Closing as no response.
