### ISSUE TITLE
Get-PNPSiteTemplate fails in List defintions or Site Security.   in Powershell V1.7.0 / Windows 10

### ISSUE THREAD

**Issue by RSCA001** [pnp/powershell#951]
After authenticating to a site  with 
Connect-PnPOnline -Url https://xxxxx/sites/MySite -Interactive -ForceAuthentication and picking an account that has ADMIN access in AAD, I run the command
Get-PnPSiteTemplate -Out C:\PSHELL\Myfile1.xml  I get  the following error on SITE SECURITY  
Get-PnPSiteTemplate : Attempted to perform an unauthorized operation.
At line:1 char:1
+ Get-PnPSiteTemplate -Out C:\PSHELL\Myfile1.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSiteTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate

When I use Connect-PnpOnline with the useWeblogin parameter , then the Get-PnpSiteTemplate command executes further, it goes through sitesecurity, and a number of other elements, but fails when analysing lists

Get-PnPSiteTemplate : GetAccessTokenAsync() called without an ACS token generator. Specify in 
AuthenticationManager constructor the authentication parameters
At line:1 char:1
+ Get-PnPSiteTemplate -Out C:\PSHELL\Myfile1.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSiteTemplate], ArgumentException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate

**Comment by FingerlessGlov3s** [comment]
In my company we recently had to regrant the admin consent against the permissions for "PnP Management Shell" Enterprise Application. This was because new permissions had been added to the application by PNP, which we hadn't allowed. It wasn't obvious that there were new permissions, but we decided to regrant the consent on the off chance it would help and soon as we did, more permissions appeared and the same errors you are seeing above disappeared.

Current permissions are as follows, if someone else comes across this issue, see if your list matches the below or make sure you have registered the PnP Management Shell" Enterprise Application, if you can't find it in Azure AD.
![image](https://user-images.githubusercontent.com/3495647/129451239-22af88a6-78a1-49d3-938b-e75a561e23c8.png)

**Comment by gautamdsheth** [comment]
Closing this due to lack of response, please create a new issue if you are still facing the issue in the latest version.
