### ISSUE TITLE
[FEATURE] Allow setting URL on New-PnPSite

### ISSUE THREAD

**Issue by kilasuit** [pnp/powershell#962]
**Is your feature request related to a problem? Please describe.**
New-SPOSite allows you to create a Site, specifying the site title & site url's as different things. New-PnPSite should allow the same for creation of Team Sites

**Describe the solution you'd like**
A url parameter on New-PnPSite that actually works with Team Sites

**Describe alternatives you've considered**
Dropping to pure CSOM or using the New-SPOSite cmdlets

**Comment by kilasuit** [comment]
Seems this **supposedly** exists but errors when trying to create a Team Site as the `URL` parameter does not exist when you try to create a Team Site - which is a terrible experience

**Comment by gautamdsheth** [comment]
Hello @kilasuit, thanks for the suggestion , this is not going to be possible because Team site are backed my M365 group and we created the cmdlets based on the API which itself doesn't have a URL option like the one for Communication sites.

So, whatever is the alias of the group, the site will take that and form the URL `/sites/Alias` or `/teams/Alias` based on setting in the SharePoint admin center.

Having said that, sometimes there is need to have different values for Group alias and SharePoint site URL. So, from tomorrow's nightly build , you can specify `SiteAlias` in the `New-PnPSite` cmdlet to create team site. If the `SiteAlias` is specified, site will be created based on that otherwise will pick up the value from the Group alias value.
